<?php
/**
 * Installer Class - Main Installation Logic
 */

class Installer {

    private const EXPECTED_TABLES = [
        'admin_notifications',
        'api_keys',
        'autori',
        'cms_pages',
        'collane',
        'consent_log',
        'contact_messages',
        'copie',
        'donazioni',
        'editori',
        'email_templates',
        'events',
        'feedback',
        'gdpr_requests',
        'generi',
        'home_content',
        'import_logs',
        'languages',
        'libri',
        'libri_autori',
        'libri_collane',
        'libri_donati',
        'libri_tag',
        'log_modifiche',
        'mensole',
        'migrations',
        // Mobile API plugin tables — active by default since 0.7.21 (schema.sql),
        // so the installer's post-import verification must check them too.
        'mobile_app_tokens',
        'mobile_availability_watchers',
        'mobile_push_log',
        'mobile_push_prefs',
        'mobile_push_subscriptions',
        'plugin_data',
        'plugin_hooks',
        'plugin_logs',
        'plugin_settings',
        'plugins',
        'posizioni',
        'preferenze_notifica_utenti',
        'prenotazioni',
        'prestiti',
        'recensioni',
        'scaffali',
        'sedi',
        'staff',
        'system_settings',
        'tag',
        'themes',
        'update_logs',
        'user_sessions',
        'utenti',
        'volumi',
        'wishlist',
        'z39_access_logs',
        'z39_rate_limits'
    ];

    private $baseDir;
    private $pdo;
    private $config = [];
    /**
     * @var array Warnings generated during trigger import
     */
    private $triggerWarnings = [];

    public function __construct($baseDir) {
        $this->baseDir = rtrim($baseDir, '/');
    }

    /**
     * Create .env file with database configuration
     */
    public function createEnvFile($host, $user, $password, $database, $port = 3306, $socket = '', $locale = 'it') {

        // Normalize locale:
        // - "it" or "it_IT" -> it_IT
        // - "en" or "en_US" -> en_US
        $normalizedLocale = str_replace('-', '_', strtolower((string)$locale));
        if ($normalizedLocale === 'en' || $normalizedLocale === 'en_us') {
            $normalizedLocale = 'en_US';
        } elseif ($normalizedLocale === 'de' || $normalizedLocale === 'de_de') {
            $normalizedLocale = 'de_DE';
        } elseif ($normalizedLocale === 'fr' || $normalizedLocale === 'fr_fr') {
            $normalizedLocale = 'fr_FR';
        } elseif ($normalizedLocale === 'it' || $normalizedLocale === 'it_it') {
            $normalizedLocale = 'it_IT';
        }

        // Fallback safety
        if (!in_array($normalizedLocale, ['it_IT', 'en_US', 'de_DE', 'fr_FR'], true)) {
            $normalizedLocale = 'it_IT';
        }

        $envPath = $this->baseDir . '/.env';

        $envContent = "# Environment Configuration - Pinakes\n";
        $envContent .= "# Generated by installer on " . date('Y-m-d H:i:s') . "\n";
        $envContent .= "# IMPORTANT: Keep this file secure and never commit it to version control\n\n";

        $envContent .= "# Database Configuration\n";
        $envContent .= "DB_HOST=" . $this->quoteEnvValue($host) . "\n";
        $envContent .= "DB_USER=" . $this->quoteEnvValue($user) . "\n";
        $envContent .= "DB_PASS=" . $this->quoteEnvValue($password) . "\n";
        $envContent .= "DB_NAME=" . $this->quoteEnvValue($database) . "\n";
        $envContent .= "DB_PORT={$port}\n";
        $envContent .= "DB_SOCKET=" . $this->quoteEnvValue($socket) . "\n\n";

        $envContent .= "# Application Environment\n";
        $envContent .= "# Set to 'production' for live environments, 'development' for local dev\n";
        $envContent .= "APP_ENV=production\n\n";

        $envContent .= "# Application Language\n";
        $envContent .= "# Default language for the entire application (e.g. it_IT, en_US)\n";
        $envContent .= "# Received: {$locale} | Normalized: {$normalizedLocale}\n";
        $envContent .= "APP_LOCALE={$normalizedLocale}\n\n";

        $envContent .= "# Debug Mode\n";
        $envContent .= "# MUST be false in production for security reasons\n";
        $envContent .= "APP_DEBUG=false\n\n";

        $envContent .= "# Encryption Key\n";
        $envContent .= "# Used to encrypt sensitive settings (e.g. plugin API keys). Regenerate if compromised.\n";
        $envContent .= "PLUGIN_ENCRYPTION_KEY=" . $this->generateEncryptionKey() . "\n\n";

        $envContent .= "# Session Security\n";
        $envContent .= "# Session lifetime in seconds (default: 3600 = 1 hour)\n";
        $envContent .= "SESSION_LIFETIME=3600\n\n";

        $envContent .= "# Display Errors\n";
        $envContent .= "# MUST be false in production (errors logged instead of displayed)\n";
        $envContent .= "DISPLAY_ERRORS=false\n\n";

        $envContent .= "# Force HTTPS\n";
        $envContent .= "# Set to 'true' only if your server supports HTTPS (requires valid SSL certificate)\n";
        $envContent .= "# Leave 'false' for local development or HTTP-only production servers\n";
        $envContent .= "FORCE_HTTPS=false\n";
        $envContent .= "\n# Canonical URL (auto-detected during installation)\n";
        $envContent .= "APP_CANONICAL_URL=" . $this->detectCanonicalUrl() . "\n";

        return file_put_contents($envPath, $envContent) !== false;
    }

    /**
     * Load database configuration from .env
     */
    public function loadEnvConfig() {
        $envPath = $this->baseDir . '/.env';

        if (!file_exists($envPath)) {
            throw new Exception(__("File .env non trovato"));
        }

        $lines = file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

        foreach ($lines as $line) {
            if (strpos($line, '=') !== false && !str_starts_with(trim($line), '#')) {
                [$key, $value] = explode('=', $line, 2);
                $this->config[trim($key)] = trim($value, '"\'');
            }
        }

        return true;
    }

    /**
     * Get database connection
     */
    public function getDatabaseConnection() {
        if ($this->pdo) {
            return $this->pdo;
        }

        $host = $this->config['DB_HOST'] ?? 'localhost';
        $port = (int)($this->config['DB_PORT'] ?? 3306);
        $database = $this->config['DB_NAME'] ?? '';
        $username = $this->config['DB_USER'] ?? 'root';
        $password = $this->config['DB_PASS'] ?? '';
        $socket = $this->config['DB_SOCKET'] ?? '';

        // Build DSN
        $dsn = "mysql:";

        if (!empty($socket)) {
            $dsn .= "unix_socket={$socket};";
        } elseif ($host === 'localhost') {
            $socketPaths = [
                '/tmp/mysql.sock',
                '/var/run/mysqld/mysqld.sock',
                '/usr/local/var/mysql/mysql.sock',
                '/opt/homebrew/var/mysql/mysql.sock'
            ];

            $found = false;
            foreach ($socketPaths as $path) {
                if (file_exists($path)) {
                    $dsn .= "unix_socket={$path};";
                    $found = true;
                    break;
                }
            }

            if (!$found) {
                $dsn .= "host={$host};port={$port};";
            }
        } else {
            $dsn .= "host={$host};port={$port};";
        }

        $dsn .= "dbname={$database};charset=utf8mb4";

        // PHP 8.5 deprecates the PDO::MYSQL_* constants in favour of the
        // driver-specific Pdo\Mysql::* constants (added in 8.4). Pick whichever
        // the running PHP provides so the installer stays warning-free on 8.5
        // without breaking 8.2–8.3 (which have no Pdo\Mysql class). constant()
        // keeps static analysis happy on the 8.2 platform baseline.
        $mysqlInitCommand = defined('Pdo\\Mysql::ATTR_INIT_COMMAND')
            ? constant('Pdo\\Mysql::ATTR_INIT_COMMAND')
            : PDO::MYSQL_ATTR_INIT_COMMAND;

        $this->pdo = new PDO($dsn, $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            $mysqlInitCommand => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        ]);

        return $this->pdo;
    }

    /**
     * Import database schema using MySQL CLI or PDO fallback
     */
    public function importSchema() {
        // Use absolute path to avoid issues with chdir()
        $installerDir = dirname(__DIR__);
        $schemaFile = $installerDir . '/database/schema.sql';

        if (!file_exists($schemaFile)) {
            // Try to resolve the real path
            $realSchemaFile = realpath($installerDir . '/database/schema.sql');
            if ($realSchemaFile === false) {
                throw new Exception("File schema.sql non trovato. Cercato in: " . $schemaFile . " (installer dir: " . $installerDir . ")");
            }
            $schemaFile = $realSchemaFile;
        }

        // Try exec() method first (faster and more reliable)
        if (function_exists('exec')) {
            try {
                return $this->importSchemaViaExec($schemaFile);
            } catch (Exception $e) {
                // If exec() fails, fall back to PDO method
                error_log("exec() method failed, falling back to PDO: " . $e->getMessage());
            }
        }

        // Fallback to PDO method (works on all hosting, including those with exec() disabled)
        return $this->importSchemaViaPDO($schemaFile);
    }

    /**
     * Import initial data (classificazione, generi, email_templates)
     */
    public function importData() {
        $installerDir = dirname(__DIR__);

        // Get locale from session first (most reliable), fallback to .env
        $locale = $_SESSION['app_locale'] ?? ($this->config['APP_LOCALE'] ?? 'it');

        // Convert locale code to full form (supports it, it_IT, en, en_US, de, de_DE, fr, fr_FR)
        $localeMap = [
            'it' => 'it_IT',
            'it_it' => 'it_IT',
            'en' => 'en_US',
            'en_us' => 'en_US',
            'de' => 'de_DE',
            'de_de' => 'de_DE',
            'fr' => 'fr_FR',
            'fr_fr' => 'fr_FR',
        ];
        $normalizedLocale = strtolower(str_replace('-', '_', $locale));
        $fullLocale = $localeMap[$normalizedLocale] ?? 'it_IT';

        // Try locale-specific data file first (data_it_IT.sql or data_en_US.sql)
        $dataFile = $installerDir . '/database/data_' . $fullLocale . '.sql';

        // If locale-specific file does not exist, do not fallback to generic data.sql
        // This enforces explicit language-specific seed files only.
        if (!file_exists($dataFile)) {
            throw new Exception(sprintf(__("File dati iniziali per la lingua selezionata non trovato: %s"), basename($dataFile)));
        }

        // Try exec() method first (faster and more reliable)
        if (function_exists('exec')) {
            try {
                return $this->importDataViaExec($dataFile);
            } catch (Exception $e) {
                error_log("exec() method failed for data import, falling back to PDO: " . $e->getMessage());
            }
        }

        // Fallback to PDO method
        return $this->importDataViaPDO($dataFile);
    }

    /**
     * Import schema using MySQL CLI (faster but requires exec())
     */
    private function importSchemaViaExec($schemaFile) {
        $host = $this->config['DB_HOST'] ?? 'localhost';
        $port = (int)($this->config['DB_PORT'] ?? 3306);
        $database = $this->config['DB_NAME'] ?? '';
        $username = $this->config['DB_USER'] ?? 'root';
        $password = $this->config['DB_PASS'] ?? '';

        // Build mysql command
        $cmd = 'mysql';
        $cmd .= ' -h ' . escapeshellarg($host);
        $cmd .= ' -P ' . (int)$port;
        $cmd .= ' -u ' . escapeshellarg($username);
        if (!empty($password)) {
            $cmd .= ' -p' . escapeshellarg($password);
        }
        $cmd .= ' --default-character-set=utf8mb4'; // Force UTF-8 to prevent encoding corruption (📚 → ðŸ"š, È → Ãˆ)
        $cmd .= ' ' . escapeshellarg($database);
        $cmd .= ' < ' . escapeshellarg($schemaFile);

        // Execute mysql command
        $output = [];
        $exitCode = 0;
        exec($cmd . ' 2>&1', $output, $exitCode);

        if ($exitCode !== 0) {
            $errorMsg = implode("\n", $output);
            throw new Exception("Errore importazione schema (exit code: $exitCode): " . $errorMsg);
        }

        return $this->verifySchemaImport();
    }

    /**
     * Import schema using PDO (works on all hosting)
     */
    private function importSchemaViaPDO($schemaFile) {
        // Read schema file
        $sql = file_get_contents($schemaFile);
        if ($sql === false) {
            throw new Exception("Impossibile leggere il file schema.sql");
        }

        // Get PDO connection
        $pdo = $this->getDatabaseConnection();

        // Split SQL into statements
        // Remove comments and handle MySQL conditional comments
        $sql = preg_replace('/--.*$/m', '', $sql); // Remove single-line comments
        $sql = preg_replace('/\/\*(?!\!).*?\*\//s', '', $sql); // Remove normal multi-line comments (not /*!... */)
        // Unwrap MySQL conditional comments: /*!40101 SET ... */ becomes just: SET ...
        $sql = preg_replace('/\/\*!\d+\s*(.*?)\s*\*\//s', '$1', $sql);

        // Split by semicolon, but handle DELIMITER statements
        $statements = [];
        $buffer = '';
        $inDelimiter = false;

        foreach (explode("\n", $sql) as $line) {
            $trimmed = trim($line);

            // Check for DELIMITER command
            if (preg_match('/^DELIMITER\s+(.+)$/i', $trimmed, $matches)) {
                $inDelimiter = true;
                continue;
            }

            $buffer .= $line . "\n";

            // Check if statement ends
            if ($inDelimiter) {
                // Looking for $$ delimiter
                if (strpos($trimmed, '$$') !== false) {
                    $statements[] = trim($buffer);
                    $buffer = '';
                    $inDelimiter = false;
                }
            } else {
                // Standard semicolon delimiter
                if (substr($trimmed, -1) === ';') {
                    $statements[] = trim($buffer);
                    $buffer = '';
                }
            }
        }

        // Add remaining buffer if any
        if (!empty(trim($buffer))) {
            $statements[] = trim($buffer);
        }

        // Execute each statement
        $executedCount = 0;
        $errors = [];

        foreach ($statements as $statement) {
            $statement = trim($statement);

            // Skip empty statements
            if (empty($statement)) {
                continue;
            }

            // Skip DELIMITER statements
            if (preg_match('/^DELIMITER/i', $statement)) {
                continue;
            }

            try {
                $pdo->exec($statement);
                $executedCount++;
            } catch (PDOException $e) {
                // Some statements might fail (like IF NOT EXISTS checks)
                // Only collect real errors
                if (strpos($e->getMessage(), 'already exists') === false) {
                    $errors[] = "Statement error: " . $e->getMessage();
                }
            }
        }

        if (!empty($errors)) {
            error_log("Schema import warnings: " . implode("\n", $errors));
            // If too many errors, throw exception with first few errors for debugging
            if (count($errors) > 10) {
                $firstErrors = array_slice($errors, 0, 5);
                throw new Exception(sprintf(__("Troppi errori durante l'import dello schema (%d errori). Primi errori:\n%s"), count($errors), implode("\n", $firstErrors)));
            }
        }

        return $this->verifySchemaImport();
    }

    /**
     * Import data using MySQL CLI (faster but requires exec())
     */
    private function importDataViaExec($dataFile) {
        $host = $this->config['DB_HOST'] ?? 'localhost';
        $port = (int)($this->config['DB_PORT'] ?? 3306);
        $database = $this->config['DB_NAME'] ?? '';
        $username = $this->config['DB_USER'] ?? 'root';
        $password = $this->config['DB_PASS'] ?? '';

        // Build mysql command
        $cmd = 'mysql';
        $cmd .= ' -h ' . escapeshellarg($host);
        $cmd .= ' -P ' . (int)$port;
        $cmd .= ' -u ' . escapeshellarg($username);
        if (!empty($password)) {
            $cmd .= ' -p' . escapeshellarg($password);
        }
        $cmd .= ' --default-character-set=utf8mb4'; // Force UTF-8 to prevent encoding corruption (📚 → ðŸ"š, È → Ãˆ)
        $cmd .= ' ' . escapeshellarg($database);
        $cmd .= ' < ' . escapeshellarg($dataFile);

        // Execute mysql command
        $output = [];
        $exitCode = 0;
        exec($cmd . ' 2>&1', $output, $exitCode);

        if ($exitCode !== 0) {
            $errorMsg = implode("\n", $output);
            throw new Exception("Errore importazione dati (exit code: $exitCode): " . $errorMsg);
        }

        return true;
    }

    /**
     * Import data using PDO (works on all hosting)
     */
    private function importDataViaPDO($dataFile) {
        // Read data file
        $sql = file_get_contents($dataFile);
        if ($sql === false) {
            throw new Exception("Impossibile leggere il file data.sql");
        }

        // Get PDO connection
        $pdo = $this->getDatabaseConnection();

        // Split SQL into statements (simpler than schema - just INSERT statements)
        $statements = array_filter(explode(";\n", $sql), function($stmt) {
            return !empty(trim($stmt));
        });

        $executedCount = 0;
        $errors = [];

        try {
            $pdo->beginTransaction();
            $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
            foreach ($statements as $statement) {
                $statement = trim($statement);

                if (empty($statement)) {
                    continue;
                }

                try {
                    $pdo->exec($statement);
                    $executedCount++;
                } catch (PDOException $e) {
                    // Collect errors but continue (some INSERTs might fail due to duplicates)
                    if (strpos($e->getMessage(), 'Duplicate entry') === false) {
                        $errors[] = "Data import error: " . $e->getMessage();
                    }
                }
            }

            if (!empty($errors)) {
                throw new Exception(sprintf(__("Errori durante l'import dei dati (%d). Primi errori:\n%s"), count($errors), implode("\n", array_slice($errors, 0, 5))));
            }

            $pdo->commit();
        } catch (\Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            throw $e;
        } finally {
            // Always restore FK checks even if execution aborts early
            try {
                $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
            } catch (PDOException $e) {
                error_log('[Installer] Failed to restore FOREIGN_KEY_CHECKS=1: ' . $e->getMessage());
            }
        }

        return true;
    }

    /**
     * Verify schema was imported correctly
     */
    private function verifySchemaImport() {
        // IMPORTANT: Close old PDO connection and reset it
        // This ensures new connections see the newly created tables
        $this->pdo = null;

        // Verify that tables were created with fresh connection
        try {
            $pdo = $this->getDatabaseConnection();
            $stmt = $pdo->query("SHOW TABLES");
            $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

            if (!is_array($tables) || empty($tables)) {
                throw new Exception("Schema non importato correttamente. Nessuna tabella trovata.");
            }

            $actual = array_map('strtolower', $tables);
            sort($actual);

            $expected = self::EXPECTED_TABLES;
            sort($expected);

            $missing = array_diff($expected, $actual);
            if (!empty($missing)) {
                throw new Exception(sprintf(__("Schema non importato correttamente. Tabelle mancanti: %s"), implode(', ', $missing)));
            }

            if (count($actual) < count($expected)) {
                throw new Exception(sprintf(__("Schema incompleto: trovate %d tabelle su %d attese."), count($actual), count($expected)));
            }
        } catch (PDOException $e) {
            throw new Exception(sprintf(__("Errore verifica tabelle: %s"), $e->getMessage()));
        }

        return true;
    }

    /**
     * Import database triggers
     */
    public function importTriggers() {
        $this->triggerWarnings = [];
        // Use absolute path to avoid issues with chdir()
        $installerDir = dirname(__DIR__);
        $triggersFile = $installerDir . '/database/triggers.sql';

        if (!file_exists($triggersFile)) {
            $this->triggerWarnings[] = "File triggers.sql non trovato — nessun trigger installato.";
            return true;
        }

        $sql = file_get_contents($triggersFile);

        if (!is_string($sql) || trim($sql) === '') {
            $this->triggerWarnings[] = "File triggers.sql vuoto — nessun trigger installato.";
            return true;
        }

        $pdo = $this->getDatabaseConnection();

        // Clean up DEFINER clauses and remove DELIMITER statements
        $sql = preg_replace('/CREATE\s+DEFINER=`[^`]+`@`[^`]+`\s+TRIGGER/i', 'CREATE TRIGGER', $sql);
        $sql = preg_replace('/DELIMITER\s+\S+/i', '', $sql);

        // Split the file into statements using '$$' as the delimiter
        $statements = explode('$$', $sql);

        $executedTriggers = 0;
        foreach ($statements as $statement) {
            $statement = trim($statement);
            if (empty($statement)) {
                continue;
            }

            try {
                $pdo->exec($statement);
                if (stripos($statement, 'CREATE TRIGGER') === 0) {
                    $executedTriggers++;
                }
            } catch (PDOException $e) {
                $message = $e->getMessage();
                $this->triggerWarnings[] = "Impossibile eseguire uno statement del trigger: {$message}";
                // Continue to the next statement
            }
        }

        if ($executedTriggers === 0 && empty($this->triggerWarnings)) {
            $this->triggerWarnings[] = "Nessun trigger valido trovato nel file triggers.sql.";
        }

        return true;
    }

    /**
     * Retrieve warnings generated during trigger import
     *
     * @return string[]
     */
    public function getTriggerWarnings(): array
    {
        return $this->triggerWarnings;
    }

    /**
     * Import optimization indexes
     * These indexes improve query performance but are not critical for basic functionality
     * Compatible with both MySQL and MariaDB
     *
     * @return bool
     */
    public function importOptimizationIndexes(): bool
    {
        $pdo = $this->getDatabaseConnection();

        // Define indexes to create (table => [index_name => columns])
        $indexes = [
            'libri' => [
                'idx_created_at' => 'created_at',
                'idx_isbn10' => 'isbn10',
                'idx_genere_scaffale' => 'genere_id, scaffale_id',
                'idx_sottogenere_scaffale' => 'sottogenere_id, scaffale_id',
                'idx_libri_tipo_media_deleted_at' => 'deleted_at, tipo_media',
            ],
            'libri_autori' => [
                'idx_libro_autore' => 'libro_id, autore_id',
                'idx_autore_libro' => 'autore_id, libro_id',
                'idx_ordine_credito' => 'ordine_credito',
                'idx_ruolo' => 'ruolo',
            ],
            'autori' => [
                'idx_nome' => 'nome(100)',
            ],
            'editori' => [
                'idx_nome' => 'nome(100)',
            ],
            'prestiti' => [
                'idx_stato_attivo' => 'stato, attivo',
                'idx_data_prestito' => 'data_prestito',
                'idx_copia_id' => 'copia_id',
                'idx_origine' => 'origine',
                'idx_libro_utente' => 'libro_id, utente_id',
            ],
            'utenti' => [
                'idx_nome' => 'nome(50)',
                'idx_cognome' => 'cognome(50)',
                'idx_nome_cognome' => 'nome(50), cognome(50)',
                'idx_tipo_utente' => 'tipo_utente',
            ],
            'generi' => [
                'idx_nome' => 'nome(50)',
            ],
            'posizioni' => [
                'idx_scaffale_mensola' => 'scaffale_id, mensola_id',
            ],
            'copie' => [
                'idx_numero_inventario' => 'numero_inventario',
                'idx_sede_id' => 'sede_id',
            ],
            'prenotazioni' => [
                'idx_libro_id' => 'libro_id',
                'idx_utente_id' => 'utente_id',
                'idx_stato' => 'stato',
                'idx_stato_libro' => 'stato, libro_id',
                'idx_queue_position' => 'queue_position',
                'idx_data_scadenza' => 'data_scadenza_prenotazione',
            ],
        ];

        foreach ($indexes as $table => $tableIndexes) {
            // Check if table exists
            try {
                $stmt = $pdo->query("SHOW TABLES LIKE " . $pdo->quote($table));
                if ($stmt->rowCount() === 0) {
                    continue; // Table doesn't exist, skip
                }
            } catch (\PDOException $e) {
                continue;
            }

            // Get existing indexes for this table
            $existingIndexes = [];
            try {
                $stmt = $pdo->query("SHOW INDEX FROM `{$table}`");
                while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                    $existingIndexes[$row['Key_name']] = true;
                }
            } catch (\PDOException $e) {
                continue;
            }

            // Create missing indexes
            foreach ($tableIndexes as $indexName => $columns) {
                if (isset($existingIndexes[$indexName])) {
                    continue; // Index already exists
                }

                try {
                    $pdo->exec("ALTER TABLE `{$table}` ADD INDEX `{$indexName}` ({$columns})");
                } catch (\PDOException $e) {
                    // Log error but continue
                    error_log("Index optimization warning ({$table}.{$indexName}): " . $e->getMessage());
                }
            }
        }

        return true;
    }

    /**
     * Verify database installation
     */
    public function verifyInstallation() {
        $pdo = $this->getDatabaseConnection();

        // Count tables
        $stmt = $pdo->query("SHOW TABLES");
        $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

        $actualTables = array_map('strtolower', $tables);
        sort($actualTables);
        $expectedTables = self::EXPECTED_TABLES;
        sort($expectedTables);

        $missing = array_diff($expectedTables, $actualTables);
        if (!empty($missing)) {
            throw new Exception(sprintf(__("Installazione database non completa. Tabelle mancanti: %s"), implode(', ', $missing)));
        }

        // Count check removed — plugins and migrations can add extra tables.
        // The missing-table check above is sufficient.

        // Check essential data
        // Note: classificazione table no longer exists - Dewey data is now in JSON files (data/dewey/)
        $stmt = $pdo->query("SELECT COUNT(*) as count FROM generi");
        $result = $stmt->fetch();
        if ($result['count'] == 0) {
            throw new Exception(__("Dati generi mancanti"));
        }


        return true;
    }

    /**
     * Create admin user
     */
    public function createAdminUser($nome, $cognome, $email, $password) {

        $pdo = $this->getDatabaseConnection();

        // Decode HTML entities that might have been added during sanitization
        $nome = html_entity_decode($nome, ENT_QUOTES, 'UTF-8');
        $cognome = html_entity_decode($cognome, ENT_QUOTES, 'UTF-8');

        // Generate unique codice_tessera
        $codiceTessera = 'ADMIN-' . date('Ymd') . '-' . str_pad((string)rand(1, 999), 3, '0', STR_PAD_LEFT);

        // Hash password
        $passwordHash = password_hash($password, PASSWORD_BCRYPT, ['cost' => 12]);

        // Resolve the locale chosen during the installer wizard. Without
        // this the new admin row falls through to the schema default for
        // utenti.locale ('it_IT'), and AuthController on first login then
        // calls I18n::setLocale('it_IT') from $row['locale'], reverting
        // the language no matter what the user picked at step 0 (#112).
        $sessionLocale = $_SESSION['app_locale'] ?? '';
        $envLocale     = $this->config['APP_LOCALE'] ?? '';
        $rawLocale     = trim((string) ($sessionLocale !== '' ? $sessionLocale : $envLocale));
        $localeMap = [
            'it' => 'it_IT', 'it_it' => 'it_IT',
            'en' => 'en_US', 'en_us' => 'en_US',
            'de' => 'de_DE', 'de_de' => 'de_DE',
            'fr' => 'fr_FR', 'fr_fr' => 'fr_FR',
        ];
        $supportedLocales = array_values(array_unique(array_values($localeMap)));
        $normalized = strtolower(str_replace('-', '_', $rawLocale));
        if (isset($localeMap[$normalized])) {
            $adminLocale = $localeMap[$normalized];
        } elseif (in_array($rawLocale, $supportedLocales, true)) {
            $adminLocale = $rawLocale;
        } else {
            $adminLocale = 'it_IT';
        }

        // Insert admin user
        $query = "
            INSERT INTO utenti (
                nome, cognome, email, password, codice_tessera,
                tipo_utente, stato, email_verificata, locale,
                data_scadenza_tessera, created_at, updated_at
            ) VALUES (
                :nome, :cognome, :email, :password, :codice_tessera,
                'admin', 'attivo', 1, :locale,
                DATE_ADD(NOW(), INTERVAL 10 YEAR), NOW(), NOW()
            )
        ";

        try {
            $stmt = $pdo->prepare($query);

            $stmt->execute([
                'nome' => $nome,
                'cognome' => $cognome,
                'email' => $email,
                'password' => $passwordHash,
                'codice_tessera' => $codiceTessera,
                'locale' => $adminLocale,
            ]);

            $userId = $pdo->lastInsertId();

            return [
                'id' => $userId,
                'codice_tessera' => $codiceTessera
            ];
        } catch (PDOException $e) {
            // A duplicate email means an admin with this address already exists —
            // e.g. re-running the installer against a database that survived while
            // the .installed marker was lost (failed-install retry, DB restore
            // without the marker, or a docroot/marker mishap). Surface a clear,
            // actionable message instead of a raw SQL error.
            if ($e->getCode() === '23000' || stripos($e->getMessage(), 'Duplicate entry') !== false) {
                throw new \RuntimeException(sprintf(
                    __("Esiste già un utente con l'email %s. Se stai reinstallando su un database esistente, accedi con le credenziali esistenti oppure usa un'altra email."),
                    $email
                ), 0, $e);
            }
            throw $e;
        }
    }

    /**
     * Save application settings to database ONLY (no more JSON file)
     */
    public function saveSetting($category, $key, $value) {
        // Try to load env if not already loaded
        if (empty($this->config)) {
            try {
                $this->loadEnvConfig();
            } catch (Exception $e) {
                throw new Exception(__("Impossibile caricare configurazione database") . ": " . $e->getMessage());
            }
        }

        // Ensure database connection is available
        try {
            $pdo = $this->getDatabaseConnection();
        } catch (Exception $e) {
            throw new Exception(__("Errore connessione database") . ": " . $e->getMessage());
        }

        if (!$pdo) {
            throw new Exception(__("Connessione database non disponibile"));
        }

        $stmt = $pdo->prepare("
            INSERT INTO system_settings (category, setting_key, setting_value, updated_at)
            VALUES (?, ?, ?, NOW())
            ON DUPLICATE KEY UPDATE setting_value = ?, updated_at = NOW()
        ");

        $valueStr = is_bool($value) ? ($value ? '1' : '0') : (string)$value;
        $stmt->execute([$category, $key, $valueStr, $valueStr]);

        return true;
    }

    /**
     * Alias for saveSetting() for backward compatibility
     */
    public function saveSettingToDatabase($category, $key, $value) {
        return $this->saveSetting($category, $key, $value);
    }

    /**
     * Upload and save logo (hardened — CR R7 / Bug-hunt #4-1).
     *
     * Defense-in-depth against arbitrary-file-write to public/assets/, which
     * sits under DocumentRoot. The installer is the most-privileged surface
     * (only reachable when the app isn't installed), so a logo upload that
     * trusts the client extension would let an attacker drop `logo_X.php`
     * straight into a web-served path.
     *
     * - Whitelist MIME via finfo (raster only — SVG dropped: it's XML and
     *   carries XSS risk via embedded <script>/onload)
     * - Derive the extension from the verified MIME, not from the client
     * - 2 MB hard cap matches SettingsController::handleLogoUpload
     * - Random filename via cryptographic RNG so an attacker can't predict
     *   the URL prior to upload
     * - chmod 0644 to prevent execution if the host ever maps the dir to PHP
     */
    public function uploadLogo($file) {
        $uploadDir = $this->baseDir . '/public/assets';

        if (!is_dir($uploadDir) && !mkdir($uploadDir, 0755, true) && !is_dir($uploadDir)) {
            throw new \RuntimeException('Impossibile creare la directory di upload');
        }

        if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            throw new \RuntimeException('Upload logo non valido');
        }
        if (($file['size'] ?? 0) > 2 * 1024 * 1024) {
            throw new \RuntimeException('Il logo supera il limite massimo di 2MB');
        }

        $allowedMimes = [
            'image/png'  => 'png',
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
        ];

        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        $mime  = $finfo ? finfo_file($finfo, $file['tmp_name']) : '';
        if ($finfo) {
            finfo_close($finfo);
        }

        if (!isset($allowedMimes[$mime])) {
            throw new \RuntimeException('Formato logo non supportato. Usa PNG, JPG o WEBP');
        }
        $extension = $allowedMimes[$mime];

        $filename    = 'logo_' . bin2hex(random_bytes(8)) . '.' . $extension;
        $destination = $uploadDir . '/' . $filename;

        if (!move_uploaded_file($file['tmp_name'], $destination)) {
            throw new \RuntimeException('Impossibile salvare il logo');
        }
        @chmod($destination, 0644);

        return '/assets/' . $filename;
    }

    /**
     * Create / repair the root .htaccess so the app routes correctly.
     *
     * REQUIRED when the document root is the project root instead of public/.
     * cPanel's File Manager hides dotfiles, so users routinely extract the ZIP
     * and move only the *visible* files into the docroot, leaving the hidden
     * root .htaccess behind. Without it nothing but "/" resolves (every route
     * and every /assets, /plugins request 404s). The installer runs PHP, so it
     * recreates the file directly on disk — invisible to File Manager, but
     * fully effective for Apache/LiteSpeed — restoring routing with zero manual
     * steps. Idempotent: existing routing (ours, hand-written, or cPanel PHP
     * directives) is preserved.
     */
    public function createHtaccess() {
        $htaccessPath = $this->baseDir . '/.htaccess';

        $pinakesBlock = <<<'HTACCESS'
# === Pinakes routing (auto-managed by the installer) ===
# Forwards all requests to the public/ subdirectory. Needed when the document
# root is the PROJECT ROOT instead of public/. Do not remove this block.
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Serve the installer and the manual-upgrade script directly
    RewriteCond %{REQUEST_URI} (^|/)installer(/|$) [NC,OR]
    RewriteCond %{REQUEST_URI} (^|/)scripts/manual-upgrade\.php$ [NC]
    RewriteRule ^ - [L]

    # Allow direct access to calendar .ics subscription files
    RewriteCond %{REQUEST_URI} ^/storage/calendar/.*\.ics$ [NC]
    RewriteRule ^ - [L]

    # Everything else is served from public/
    RewriteCond %{REQUEST_URI} !^/public/
    RewriteRule ^(.*)$ public/$1 [L,QSA]
</IfModule>

# Prevent directory browsing
<IfModule mod_autoindex.c>
    Options -Indexes
</IfModule>

# Block access to sensitive files at the project root
<FilesMatch "^(\.env|\.env\..+|\.git.*|\.installed|composer\.(json|lock)|package(-lock)?\.json|CLAUDE\.md)$">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order deny,allow
        Deny from all
    </IfModule>
</FilesMatch>
# === end Pinakes routing ===
HTACCESS;

        if (file_exists($htaccessPath)) {
            $existing = (string) @file_get_contents($htaccessPath);
            // Already routed? (our marker, a hand-written rule, or the packaged one)
            if (strpos($existing, '=== Pinakes routing') !== false
                || strpos($existing, 'public/$1') !== false) {
                return true;
            }
            // A file exists but lacks routing (e.g. cPanel only wrote its PHP
            // directives). Append our block, preserving the existing content.
            $merged = rtrim($existing, "\n") . "\n\n" . $pinakesBlock . "\n";
            return file_put_contents($htaccessPath, $merged) !== false;
        }

        // No .htaccess at all — write the full routing block.
        return file_put_contents($htaccessPath, $pinakesBlock . "\n") !== false;
    }

    /**
     * Create installation lock file
     */
    public function createLockFile() {
        $lockFile = dirname(dirname(__DIR__)) . '/.installed';
        $lockContent = "Installed on: " . date('Y-m-d H:i:s') . "\n";
        $lockContent .= "Do not delete this file. It prevents re-installation.\n";

        return file_put_contents($lockFile, $lockContent) !== false;
    }

    /**
     * Check if installer is locked (already installed)
     */
    public function isInstalled() {
        return file_exists(dirname(dirname(__DIR__)) . '/.installed');
    }

    /**
     * Populate default system settings
     */
    public function populateDefaultSettings() {
        $defaults = [
            // Registration
            ['registration', 'require_admin_approval', '1'],

            // Contacts (empty defaults)
            ['contacts', 'contact_email', ''],
            ['contacts', 'contact_phone', ''],
            ['contacts', 'notification_email', ''],

            // Privacy
            ['privacy', 'cookie_banner_enabled', '0'],
        ];

        $locale = $this->getInstallerLocale();
        $localized = $this->getLocaleDefaultTexts($locale);

        foreach ($localized['app'] ?? [] as $key => $value) {
            $defaults[] = ['app', $key, $value];
        }

        foreach ($localized['contacts'] ?? [] as $key => $value) {
            $defaults[] = ['contacts', $key, $value];
        }

        foreach ($localized['privacy'] ?? [] as $key => $value) {
            $defaults[] = ['privacy', $key, $value];
        }

        foreach ($localized['cookie_banner'] ?? [] as $key => $value) {
            $defaults[] = ['cookie_banner', $key, $value];
        }

        foreach ($defaults as [$category, $key, $value]) {
            try {
                $this->saveSetting($category, $key, $value);
            } catch (Exception $e) {
                // Ignore if already exists
            }
        }

        // Persist selected locale for the application
        $this->saveSetting('app', 'locale', $locale);
        $this->setDefaultLanguage($locale);

        return true;
    }

    /**
     * Detect canonical URL of the current installation request.
     */
    private function detectCanonicalUrl(): string
    {
        $scheme = 'http';

        if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
            $forwardedProto = explode(',', (string)$_SERVER['HTTP_X_FORWARDED_PROTO'])[0];
            $scheme = strtolower($forwardedProto) === 'https' ? 'https' : 'http';
        } elseif (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
            $scheme = 'https';
        } elseif (!empty($_SERVER['REQUEST_SCHEME'])) {
            $scheme = strtolower((string)$_SERVER['REQUEST_SCHEME']) === 'https' ? 'https' : 'http';
        } elseif (isset($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443) {
            $scheme = 'https';
        }

        $host = 'localhost';
        if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $host = explode(',', (string)$_SERVER['HTTP_X_FORWARDED_HOST'])[0];
        } elseif (!empty($_SERVER['HTTP_HOST'])) {
            $host = (string)$_SERVER['HTTP_HOST'];
        } elseif (!empty($_SERVER['SERVER_NAME'])) {
            $host = (string)$_SERVER['SERVER_NAME'];
        }

        $port = null;
        $host = trim($host);
        if (preg_match('/^\[(.+)\](?::(\d+))?$/', $host, $matches)) {
            // Bracketed IPv6 literal, optionally with port
            $host = '[' . $matches[1] . ']';
            $port = isset($matches[2]) ? (int) $matches[2] : null;
        } elseif (substr_count($host, ':') === 1) {
            // hostname:port or IPv4:port
            [$hostOnly, $portPart] = explode(':', $host, 2);
            $host = $hostOnly;
            $port = is_numeric($portPart) ? (int)$portPart : null;
        } elseif (strpos($host, ':') !== false) {
            // Unbracketed IPv6 literal (no explicit port)
            $host = '[' . trim($host, '[]') . ']';
        }

        if ($port === null) {
            if (!empty($_SERVER['HTTP_X_FORWARDED_PORT'])) {
                $port = (int)$_SERVER['HTTP_X_FORWARDED_PORT'];
            } elseif (isset($_SERVER['SERVER_PORT']) && is_numeric((string)$_SERVER['SERVER_PORT'])) {
                $port = (int)$_SERVER['SERVER_PORT'];
            }
        }

        $base = $scheme . '://' . $host;
        $defaultPorts = ['http' => 80, 'https' => 443];
        if ($port !== null && $defaultPorts[$scheme] !== $port) {
            $base .= ':' . $port;
        }

        return rtrim($base, '/');
    }

    private function generateEncryptionKey(): string
    {
        try {
            $bytes = random_bytes(32);
            return 'base64:' . base64_encode($bytes);
        } catch (\Throwable $e) {
            return 'base64:' . base64_encode(hash('sha256', uniqid((string)mt_rand(), true), true));
        }
    }

    /**
     * Quote a value for .env file if it contains special characters.
     * Values with spaces, #, =, quotes, or other special chars need double-quoting.
     */
    private function quoteEnvValue(string $value): string
    {
        // Empty string should be quoted
        if ($value === '') {
            return '""';
        }

        // Check if value needs quoting (contains special chars)
        if (preg_match('/[\s#="\'\\\\$`!]/', $value)) {
            // Escape backslashes, double quotes, and $ (prevent shell/variable expansion)
            $escaped = str_replace(['\\', '"', '$'], ['\\\\', '\\"', '\\$'], $value);
            return '"' . $escaped . '"';
        }

        return $value;
    }

    /**
     * Update a variable in the .env file
     * @param string $key Variable name (e.g., 'APP_CANONICAL_URL')
     * @param string $value New value
     * @return bool Success status
     */
    public function updateEnvVariable(string $key, string $value): bool
    {
        $envPath = $this->baseDir . '/.env';

        if (!file_exists($envPath)) {
            return false;
        }

        $envContent = file_get_contents($envPath);
        if ($envContent === false) {
            return false;
        }

        // Escape special regex characters in key
        $escapedKey = preg_quote($key, '/');

        // Pattern to match the key with any value (handles empty values too)
        $pattern = '/^' . $escapedKey . '=.*$/m';

        // New line content (quote the value to handle spaces, #, $, etc.)
        $replacement = $key . '=' . $this->quoteEnvValue($value);

        // Replace the line (use callback to avoid $ backreference issues)
        if (preg_match($pattern, $envContent)) {
            $newContent = preg_replace_callback(
                $pattern,
                static fn () => $replacement,
                $envContent
            );
        } else {
            // If key doesn't exist, append it
            $newContent = rtrim($envContent) . "\n" . $replacement . "\n";
        }

        return file_put_contents($envPath, $newContent) !== false;
    }

    private function getInstallerLocale(): string
    {
        $locale = $this->config['APP_LOCALE'] ?? 'it_IT';
        $locale = str_replace('-', '_', strtolower($locale));
        if ($locale === 'en' || $locale === 'en_us') {
            return 'en_US';
        }
        if ($locale === 'de' || $locale === 'de_de') {
            return 'de_DE';
        }
        if ($locale === 'fr' || $locale === 'fr_fr') {
            return 'fr_FR';
        }
        if ($locale === 'it' || $locale === 'it_it') {
            return 'it_IT';
        }
        return 'it_IT';
    }

    private function getLocaleDefaultTexts(string $locale): array
    {
        static $texts = null;

        if ($texts === null) {
            $path = $this->baseDir . '/config/default_texts.php';
            if (is_file($path)) {
                $texts = require $path;
            } else {
                $texts = [];
            }
        }

        $fallback = $texts['it_IT'] ?? [];
        if ($locale === 'it_IT' || !isset($texts[$locale])) {
            return $fallback;
        }

        return $this->mergeLocaleDefaults($fallback, $texts[$locale]);
    }

    private function mergeLocaleDefaults(array $base, array $override): array
    {
        foreach ($override as $key => $value) {
            if (is_array($value) && isset($base[$key]) && is_array($base[$key])) {
                $base[$key] = $this->mergeLocaleDefaults($base[$key], $value);
            } else {
                $base[$key] = $value;
            }
        }

        return $base;
    }

    private function setDefaultLanguage(string $locale): void
    {
        $pdo = $this->getDatabaseConnection();

        $pdo->exec("UPDATE languages SET is_default = 0");

        $stmt = $pdo->prepare("UPDATE languages SET is_default = 1 WHERE code = :code LIMIT 1");
        $stmt->execute(['code' => $locale]);
    }

    /**
     * Install Open Library plugin automatically during installation
     */
    public function installOpenLibraryPlugin() {
        $pluginSourceDir = $this->baseDir . '/storage/plugins/open-library';
        $pluginDestDir = $this->baseDir . '/storage/plugins';

        // Ensure plugins directory exists
        if (!is_dir($pluginDestDir)) {
            mkdir($pluginDestDir, 0755, true);
        }

        // Plugin should already be in storage/plugins/open-library from the repository
        if (!is_dir($pluginSourceDir)) {
            throw new Exception("Open Library plugin not found in storage/plugins/open-library");
        }

        // Get database connection
        $pdo = $this->getDatabaseConnection();

        // Insert plugin record only if not already installed
        $stmt = $pdo->prepare("SELECT id FROM plugins WHERE name = 'open-library' LIMIT 1");
        $stmt->execute();
        $pluginId = (int)$stmt->fetchColumn();

        if (!$pluginId) {
            $stmt = $pdo->prepare("
                INSERT INTO plugins (
                    name, display_name, description, version, author, author_url, plugin_url,
                    is_active, path, main_file, requires_php, requires_app, metadata, installed_at
                ) VALUES (
                    'open-library',
                    'Open Library Scraper',
                    'Integrates Open Library and Google Books APIs for comprehensive book metadata scraping. Supports ISBN lookup with multi-source fallback and encrypted API key storage.',
                    '1.0.0',
                    'Fabiodalez',
                    '',
                    '',
                    1,
                    'open-library',
                    'wrapper.php',
                    '8.2',
                    '1.0.0',
                    '{}',
                    NOW()
                )
            ");

            $stmt->execute();
            $pluginId = (int)$pdo->lastInsertId();
        }

        if (!$pluginId) {
            throw new Exception(__("Impossibile determinare l'ID del plugin Open Library."));
        }

        // Register plugin hooks (avoid duplicates)
        $existingHooksStmt = $pdo->prepare("SELECT hook_name, callback_method FROM plugin_hooks WHERE plugin_id = ?");
        $existingHooksStmt->execute([$pluginId]);
        $existingHooks = $existingHooksStmt->fetchAll(PDO::FETCH_ASSOC);

        $existingMap = [];
        foreach ($existingHooks as $hook) {
            $existingMap[$hook['hook_name'] . '|' . $hook['callback_method']] = true;
        }

        $hooks = [
            ['scrape.sources', 'addOpenLibrarySource', 5],
            ['scrape.fetch.custom', 'fetchFromOpenLibrary', 5],
            ['scrape.data.modify', 'enrichWithOpenLibraryData', 10],
        ];

        foreach ($hooks as [$hookName, $callbackMethod, $priority]) {
            $key = $hookName . '|' . $callbackMethod;
            if (isset($existingMap[$key])) {
                continue;
            }

            $stmt = $pdo->prepare("
                INSERT INTO plugin_hooks (plugin_id, hook_name, callback_class, callback_method, priority, is_active, created_at)
                VALUES (?, ?, 'OpenLibraryPlugin', ?, ?, 1, NOW())
            ");

            $stmt->execute([$pluginId, $hookName, $callbackMethod, $priority]);
        }

        return $pluginId;
    }

    /**
     * Register and activate default plugins
     * Plugins: open-library, z39-server, api-book-scraper, digital-library, dewey-editor
     * Excluded: scraping-pro (commercial/proprietary)
     */
    public function installPluginsFromZip() {
        $pdo = $this->getDatabaseConnection();
        $results = [];

        // Helper to ensure hooks exist
        $ensureHooks = function(int $pluginId, array $hooks, string $callbackClass) use ($pdo) {
            $existing = $pdo->prepare("SELECT hook_name, callback_method FROM plugin_hooks WHERE plugin_id = ?");
            $existing->execute([$pluginId]);
            $existingMap = [];
            foreach ($existing->fetchAll(PDO::FETCH_ASSOC) as $row) {
                $existingMap[$row['hook_name'] . '|' . $row['callback_method']] = true;
            }

            foreach ($hooks as $hook) {
                $hookName = $hook['name'];
                if (empty($hook['callback_method'])) {
                    // Skip hooks without explicit callback_method — auto-generated names
                    // like "handleScrapefetchcustom" don't match real plugin methods
                    continue;
                }
                $callbackMethod = $hook['callback_method'];
                $priority = $hook['priority'] ?? 10;
                $key = $hookName . '|' . $callbackMethod;
                if (isset($existingMap[$key])) {
                    continue;
                }

                $stmt = $pdo->prepare("
                    INSERT INTO plugin_hooks (plugin_id, hook_name, callback_class, callback_method, priority, is_active, created_at)
                    VALUES (?, ?, ?, ?, ?, 1, NOW())
                ");
                $stmt->execute([$pluginId, $hookName, $callbackClass, $callbackMethod, $priority]);
            }
        };

        // Generic plugin installer
        $installPlugin = function(string $pluginName, array $additionalHooks = []) use ($pdo, $ensureHooks, &$results) {
            try {
                $pluginDir = $this->baseDir . '/storage/plugins/' . $pluginName;

                if (!is_dir($pluginDir)) {
                    $results[] = ['name' => $pluginName, 'status' => 'error', 'message' => 'Directory not found'];
                    return;
                }

                $pluginJsonPath = $pluginDir . '/plugin.json';
                if (!file_exists($pluginJsonPath)) {
                    $results[] = ['name' => $pluginName, 'status' => 'error', 'message' => 'plugin.json not found'];
                    return;
                }

                $pluginJson = json_decode(file_get_contents($pluginJsonPath), true);
                if (!$pluginJson) {
                    $results[] = ['name' => $pluginName, 'status' => 'error', 'message' => 'Invalid plugin.json'];
                    return;
                }

                $stmt = $pdo->prepare("SELECT id FROM plugins WHERE name = :name LIMIT 1");
                $stmt->execute(['name' => $pluginJson['name']]);
                $pluginId = (int)$stmt->fetchColumn();

                if (!$pluginId) {
                    $insertStmt = $pdo->prepare("
                        INSERT INTO plugins (name, display_name, description, version, author, author_url, plugin_url,
                            is_active, path, main_file, requires_php, requires_app, metadata, installed_at)
                        VALUES (:name, :display_name, :description, :version, :author, :author_url, :plugin_url,
                            1, :path, :main_file, :requires_php, :requires_app, :metadata, NOW())
                    ");

                    $insertStmt->execute([
                        'name' => $pluginJson['name'],
                        'display_name' => $pluginJson['display_name'],
                        'description' => $pluginJson['description'],
                        'version' => $pluginJson['version'],
                        'author' => $pluginJson['author'] ?? '',
                        'author_url' => $pluginJson['author_url'] ?? '',
                        'plugin_url' => $pluginJson['plugin_url'] ?? '',
                        'path' => $pluginName,
                        'main_file' => $pluginJson['main_file'],
                        'requires_php' => $pluginJson['requires_php'] ?? '8.0',
                        'requires_app' => $pluginJson['requires_app'] ?? '1.0',
                        'metadata' => json_encode($pluginJson['metadata'] ?? [])
                    ]);

                    $pluginId = (int)$pdo->lastInsertId();
                }

                // Register hooks from plugin.json
                $hooks = $pluginJson['metadata']['hooks'] ?? [];
                // Merge with additional hooks
                $hooks = array_merge($hooks, $additionalHooks);

                // Determine callback class from plugin name (CamelCase convention)
                $callbackClass = str_replace(' ', '', ucwords(str_replace('-', ' ', $pluginName))) . 'Plugin';

                if (!empty($hooks)) {
                    $ensureHooks($pluginId, $hooks, $callbackClass);
                }

                $results[] = ['name' => $pluginName, 'status' => 'installed_and_activated', 'plugin_id' => $pluginId];

            } catch (Exception $e) {
                $results[] = ['name' => $pluginName, 'status' => 'error', 'message' => $e->getMessage()];
            }
        };

        // NOTE: The 5 historically-default plugins plus mobile-api (active by default
        // since 0.7.21) are auto-activated on fresh install.
        // Other bundled plugins (BundledPlugins::LIST) are registered later by
        // autoRegisterBundledPlugins() and remain deactivated until admin opt-in.
        // Keeping new plugins opt-in is safer for fresh installs: it avoids surprising
        // behavior changes, side effects (extra routes, DB tables, background jobs),
        // and lets the admin review and enable each plugin consciously.
        // Install all default plugins (excluding scraping-pro)
        $installPlugin('open-library');
        $installPlugin('z39-server', [
            ['name' => 'app.routes.register', 'callback_method' => 'registerRoutes', 'priority' => 10],
            ['name' => 'scrape.fetch.custom', 'callback_method' => 'fetchBookMetadata', 'priority' => 3]
        ]);
        $installPlugin('api-book-scraper');
        $installPlugin('digital-library', [
            ['name' => 'app.routes.register', 'callback_method' => 'registerRoutes', 'priority' => 10]
        ]);
        $installPlugin('dewey-editor', [
            ['name' => 'app.routes.register', 'callback_method' => 'registerRoutes', 'priority' => 10]
        ]);
        // Mobile API: active by default since 0.7.21 so a fresh install ships a
        // working /api/v1 for the companion Android app out of the box. Its tables
        // are created by schema.sql (mirrors MobileApiPlugin::ensureSchema). Existing
        // installs get it shipped + registered but INACTIVE on upgrade — admin opts in.
        $installPlugin('mobile-api', [
            ['name' => 'app.routes.register', 'callback_method' => 'registerRoutes', 'priority' => 10],
            ['name' => 'mobile_api.dispatch_push', 'callback_method' => 'dispatchPush', 'priority' => 20]
        ]);

        // Configure Z39 Server with SBN (Servizio Bibliotecario Nazionale) as default
        $this->configureZ39DefaultSettings($pdo);

        return $results;
    }

    /**
     * Configure Z39 Server plugin with locale-appropriate default servers
     *
     * For Italian installations: Only SBN (JSON API) is enabled by default
     * For English installations: SBN + European SRU servers (K10plus, SUDOC, DNB)
     *
     * This prevents author name format inconsistencies when scraping from multiple
     * sources. SBN returns consistent "Surname, Name" format which gets normalized.
     * Foreign servers may return different formats that could cause duplicates.
     *
     * @param PDO $pdo Database connection
     */
    private function configureZ39DefaultSettings(PDO $pdo): void
    {
        try {
            // Get Z39 Server plugin ID
            $stmt = $pdo->prepare("SELECT id FROM plugins WHERE name = 'z39-server' LIMIT 1");
            $stmt->execute();
            $pluginId = (int)$stmt->fetchColumn();

            if (!$pluginId) {
                return; // Plugin not installed
            }

            // Check installation locale from session
            // Session value can be 'it' or 'en_US' (from step0.php form)
            // Use str_starts_with for robustness in case locale format changes
            $locale = $_SESSION['app_locale'] ?? 'it';
            $isItalian = str_starts_with($locale, 'it');

            // Default Z39.50/SRU servers configuration
            // Italian installations: Empty array - only SBN (JSON API) will be used
            // English installations: Include European SRU servers for broader coverage
            if ($isItalian) {
                // Italian: Only SBN (prevents author name format inconsistencies)
                $defaultServers = json_encode([]);
            } else {
                // English: Include European SRU servers
                // K10plus (Germany) is the most reliable European SRU server
                // SUDOC (France) is good for European books
                // DNB (Germany) has comprehensive German-language coverage
                $defaultServers = json_encode([
                    [
                        'name' => 'K10plus (GBV Germany)',
                        'url' => 'https://sru.k10plus.de/opac-de-627',
                        'database' => 'opac-de-627',
                        'syntax' => 'marcxml',
                        'enabled' => true,
                        'timeout' => 15,
                        'indexes' => ['isbn' => 'pica.isb']
                    ],
                    [
                        'name' => 'SUDOC (France)',
                        'url' => 'https://www.sudoc.abes.fr/cbs/sru/',
                        'database' => '',
                        'syntax' => 'unimarc',
                        'enabled' => true,
                        'timeout' => 15,
                        'indexes' => ['isbn' => 'isb']
                    ],
                    [
                        'name' => 'DNB - Deutsche Nationalbibliothek',
                        'url' => 'https://services.dnb.de/sru/dnb',
                        'database' => 'dnb',
                        'syntax' => 'marcxml',
                        'enabled' => true,
                        'timeout' => 15,
                        'indexes' => ['isbn' => 'num']
                    ]
                ]);
            }

            // Default settings for Z39 Server
            $defaultSettings = [
                'enable_client' => '1',           // Enable Z39.50 client for scraping
                'servers' => $defaultServers,     // Empty for IT, K10plus+SUDOC+DNB for EN
                'server_enabled' => '1',          // Enable SRU server mode
                'enable_server' => '1',
                'max_records' => '100',
                'default_records' => '10',
                'supported_formats' => 'marcxml,dc,mods,oai_dc',
                'default_format' => 'marcxml',
                'rate_limit_enabled' => '1',
                'rate_limit_requests' => '100',
                'rate_limit_window' => '3600',
                'enable_logging' => '1',
                'cql_version' => '1.2',
                'sru_version' => '1.2',
                // SBN (Italian National Library) - enabled by default for ALL locales
                // SBN provides excellent coverage for Italian books and many international titles
                'enable_sbn' => '1',              // Enable SBN JSON API client
                'sbn_timeout' => '15'             // SBN request timeout in seconds
            ];

            // Insert settings (skip if already exist)
            $insertStmt = $pdo->prepare("
                INSERT IGNORE INTO plugin_settings (plugin_id, setting_key, setting_value, autoload, created_at)
                VALUES (:plugin_id, :key, :value, 1, NOW())
            ");

            foreach ($defaultSettings as $key => $value) {
                $insertStmt->execute([
                    'plugin_id' => $pluginId,
                    'key' => $key,
                    'value' => $value
                ]);
            }

        } catch (Exception $e) {
            // Log but don't fail installation
            error_log('[Installer] Failed to configure Z39 defaults: ' . $e->getMessage());
        }
    }

    /**
     * Set secure file permissions after installation
     * - Directories: 755 (rwxr-xr-x)
     * - Files: 644 (rw-r--r--)
     * - Writable directories (storage, logs): 775
     * - Sensitive files (.env): 600
     *
     * @return array Results with counts of modified items
     */
    public function setSecurePermissions(): array
    {
        $results = [
            'directories' => 0,
            'files' => 0,
            'writable_dirs' => 0,
            'sensitive_files' => 0,
            'errors' => []
        ];

        // Directories that need write permissions (775)
        $writableDirs = [
            'storage',
            'storage/cache',
            'storage/logs',
            'storage/plugins',
            'storage/uploads',
            'storage/uploads/plugins',
            'storage/backups',
            'storage/tmp',
            'storage/sessions',
            'cache',
            'tmp',
            'public/assets',
            'public/uploads',
            'public/uploads/autori',
        ];

        // Sensitive files that need restricted permissions (600)
        $sensitiveFiles = [
            '.env',
            '.installed',
        ];

        // Directories to skip (vendor, node_modules, .git)
        $skipDirs = ['vendor', 'node_modules', '.git', 'installer'];

        // First, handle sensitive files
        foreach ($sensitiveFiles as $file) {
            $path = $this->baseDir . '/' . $file;
            if (file_exists($path)) {
                if (@chmod($path, 0600)) {
                    $results['sensitive_files']++;
                } else {
                    $results['errors'][] = "Cannot set permissions on: $file";
                }
            }
        }

        // Handle writable directories first (create if missing)
        foreach ($writableDirs as $dir) {
            $path = $this->baseDir . '/' . $dir;
            if (!is_dir($path)) {
                @mkdir($path, 0775, true);
            }
            if (is_dir($path)) {
                if (@chmod($path, 0775)) {
                    $results['writable_dirs']++;
                } else {
                    $results['errors'][] = "Cannot set permissions on directory: $dir";
                }
            }
        }

        // Recursively set permissions on all other files and directories
        $this->setPermissionsRecursive(
            $this->baseDir,
            $skipDirs,
            $writableDirs,
            $sensitiveFiles,
            $results
        );

        return $results;
    }

    /**
     * Recursively set permissions on files and directories
     */
    private function setPermissionsRecursive(
        string $dir,
        array $skipDirs,
        array $writableDirs,
        array $sensitiveFiles,
        array &$results,
        string $relativePath = ''
    ): void {
        if (!is_dir($dir)) {
            return;
        }

        $items = @scandir($dir);
        if ($items === false) {
            return;
        }

        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $dir . '/' . $item;
            $relPath = $relativePath ? $relativePath . '/' . $item : $item;

            // Skip certain directories
            if (is_dir($path) && in_array($item, $skipDirs)) {
                continue;
            }

            // Skip files/dirs we already handled
            if (in_array($relPath, $sensitiveFiles)) {
                continue;
            }

            // Check if this is a writable directory (or inside one)
            $isWritableDir = false;
            foreach ($writableDirs as $wDir) {
                if ($relPath === $wDir || strpos($relPath, $wDir . '/') === 0) {
                    $isWritableDir = true;
                    break;
                }
            }

            if (is_dir($path)) {
                // Set directory permissions
                $targetPerm = $isWritableDir ? 0775 : 0755;
                if (@chmod($path, $targetPerm)) {
                    $results['directories']++;
                }

                // Recurse into subdirectory
                $this->setPermissionsRecursive(
                    $path,
                    $skipDirs,
                    $writableDirs,
                    $sensitiveFiles,
                    $results,
                    $relPath
                );
            } else {
                // Set file permissions (644 for normal, 664 for files in writable dirs)
                $targetPerm = $isWritableDir ? 0664 : 0644;
                if (@chmod($path, $targetPerm)) {
                    $results['files']++;
                }
            }
        }
    }

    /**
     * Delete installer directory for security
     */
    public function deleteInstaller() {
        $installerDir = dirname(__DIR__);
        return $this->recursiveDelete($installerDir);
    }

    /**
     * Recursively delete directory
     */
    private function recursiveDelete($dir) {
        if (!is_dir($dir)) {
            return false;
        }

        $files = array_diff(scandir($dir), ['.', '..']);

        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            is_dir($path) ? $this->recursiveDelete($path) : unlink($path);
        }

        return rmdir($dir);
    }
}
