<?php

return [
    'it_IT' => [
        'app' => [
            'footer_description' => 'Il tuo sistema Pinakes per catalogare, gestire e condividere la tua collezione libraria.',
        ],
        'contacts' => [
            'page_title' => 'Contattaci',
            'page_content' => '<p>Contattaci per qualsiasi informazione.</p>',
            'privacy_text' => 'I tuoi dati sono protetti secondo la nostra privacy policy.',
        ],
        'privacy' => [
            'page_title' => 'Privacy Policy',
            'page_content' => '<p>La tua privacy è importante per noi.</p>',
            'cookie_banner_language' => 'it',
            'cookie_banner_country' => 'IT',
            'cookie_policy_content' => '<p>Questa pagina descrive come utilizziamo i cookie sul nostro sito.</p>',
        ],
        'cookie_banner' => [
            'banner_description' => '<p>Utilizziamo i cookie per migliorare la tua esperienza. Continuando a visitare questo sito, accetti il nostro uso dei cookie.</p>',
            'accept_all_text' => 'Accetta tutti',
            'reject_non_essential_text' => 'Rifiuta non essenziali',
            'save_selected_text' => 'Accetta selezionati',
            'preferences_button_text' => 'Preferenze',
            'preferences_title' => 'Personalizza le tue preferenze sui cookie',
            'preferences_description' => '<p>Rispettiamo il tuo diritto alla privacy. Puoi scegliere di non consentire alcuni tipi di cookie. Le tue preferenze si applicheranno all\'intero sito web.</p>',
            'cookie_essential_name' => 'Cookie Essenziali',
            'cookie_essential_description' => 'Questi cookie sono necessari per il funzionamento del sito e non possono essere disabilitati.',
            'cookie_analytics_name' => 'Cookie Analitici',
            'cookie_analytics_description' => 'Questi cookie ci aiutano a capire come i visitatori interagiscono con il sito web.',
            'cookie_marketing_name' => 'Cookie di Marketing',
            'cookie_marketing_description' => 'Questi cookie vengono utilizzati per fornire annunci personalizzati.',
        ],
    ],
    'en_US' => [
        'app' => [
            'footer_description' => 'Your Pinakes system to catalog, manage, and share your book collection.',
        ],
        'contacts' => [
            'page_title' => 'Contact Us',
            'page_content' => '<p>Contact us for any information.</p>',
            'privacy_text' => 'Your data is protected according to our privacy policy.',
        ],
        'privacy' => [
            'page_title' => 'Privacy Policy',
            'page_content' => '<p>Your privacy matters to us.</p>',
            'cookie_banner_language' => 'en',
            'cookie_banner_country' => 'US',
            'cookie_policy_content' => '<p>This page explains how we use cookies on our website.</p>',
        ],
        'cookie_banner' => [
            'banner_description' => '<p>We use cookies to improve your experience. By continuing to browse this site, you agree to our use of cookies.</p>',
            'accept_all_text' => 'Accept all',
            'reject_non_essential_text' => 'Reject non-essential',
            'save_selected_text' => 'Accept selected',
            'preferences_button_text' => 'Preferences',
            'preferences_title' => 'Customize your cookie preferences',
            'preferences_description' => '<p>We respect your right to privacy. You can choose not to allow some types of cookies. Your preferences will apply across the entire website.</p>',
            'cookie_essential_name' => 'Essential Cookies',
            'cookie_essential_description' => 'These cookies are required for the website to function and cannot be disabled.',
            'cookie_analytics_name' => 'Analytics Cookies',
            'cookie_analytics_description' => 'These cookies help us understand how visitors interact with the website.',
            'cookie_marketing_name' => 'Marketing Cookies',
            'cookie_marketing_description' => 'These cookies are used to deliver personalized advertisements.',
        ],
    ],
    'fr_FR' => [
        'app' => [
            'footer_description' => 'Votre système Pinakes pour cataloguer, gérer et partager votre collection de livres.',
        ],
        'contacts' => [
            'page_title' => 'Contactez-nous',
            'page_content' => '<p>Contactez-nous pour toute information.</p>',
            'privacy_text' => 'Vos données sont protégées conformément à notre politique de confidentialité.',
        ],
        'privacy' => [
            'page_title' => 'Politique de confidentialité',
            'page_content' => '<p>Votre vie privée est importante pour nous.</p>',
            'cookie_banner_language' => 'fr',
            'cookie_banner_country' => 'FR',
            'cookie_policy_content' => '<p>Cette page explique comment nous utilisons les cookies sur notre site web.</p>',
        ],
        'cookie_banner' => [
            'banner_description' => '<p>Nous utilisons des cookies pour améliorer votre expérience. En continuant à naviguer sur ce site, vous acceptez notre utilisation des cookies.</p>',
            'accept_all_text' => 'Tout accepter',
            'reject_non_essential_text' => 'Refuser les non essentiels',
            'save_selected_text' => 'Accepter la sélection',
            'preferences_button_text' => 'Préférences',
            'preferences_title' => 'Personnaliser vos préférences en matière de cookies',
            'preferences_description' => '<p>Nous respectons votre droit à la vie privée. Vous pouvez choisir de ne pas autoriser certains types de cookies. Vos préférences s\'appliqueront à l\'ensemble du site web.</p>',
            'cookie_essential_name' => 'Cookies essentiels',
            'cookie_essential_description' => 'Ces cookies sont nécessaires au fonctionnement du site et ne peuvent pas être désactivés.',
            'cookie_analytics_name' => 'Cookies analytiques',
            'cookie_analytics_description' => 'Ces cookies nous aident à comprendre comment les visiteurs interagissent avec le site web.',
            'cookie_marketing_name' => 'Cookies marketing',
            'cookie_marketing_description' => 'Ces cookies sont utilisés pour diffuser des publicités personnalisées.',
        ],
    ],
];
