-- Initial data for Pinakes
-- Generated by installer

SET FOREIGN_KEY_CHECKS=0;

-- Genres (French translations)
INSERT IGNORE INTO `generi` VALUES (1,'Prose',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT IGNORE INTO `generi` VALUES (2,'Poésie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT IGNORE INTO `generi` VALUES (3,'Théâtre',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT IGNORE INTO `generi` VALUES (4,'Récit',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT IGNORE INTO `generi` VALUES (5,'Essai',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT IGNORE INTO `generi` VALUES (6,'Rhétorique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT IGNORE INTO `generi` VALUES (7,'Épopée',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT IGNORE INTO `generi` VALUES (8,'Poésie didactique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT IGNORE INTO `generi` VALUES (9,'Poésie lyrique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT IGNORE INTO `generi` VALUES (10,'Théâtre parlé',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',3);
INSERT IGNORE INTO `generi` VALUES (11,'Théâtre musical',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',3);
INSERT IGNORE INTO `generi` VALUES (12,'Roman - Fragment',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (13,'Roman - historique - histoire alternative',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (14,'Roman - historique - uchronie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (15,'Roman - historique - cape et épée',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (16,'Roman - historique - péplum',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (17,'Roman - Science-Fiction - SF technologique - Singularity Fiction',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (18,'Roman - Science-Fiction - SF technologique - Cyberpunk - Postcyberpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (19,'Roman - Science-Fiction - SF technologique - Cyberpunk - Biopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (20,'Roman - Science-Fiction - SF technologique - Cyberpunk - Nanopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (21,'Roman - Science-Fiction - SF technologique - Cyberpunk - Dieselpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (22,'Roman - Science-Fiction - SF technologique - Cyberpunk - Decopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (23,'Roman - Science-Fiction - SF technologique - Cyberpunk - Swordpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (24,'Roman - Science-Fiction - SF technologique - Cyberpunk - Sandalpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (25,'Roman - Science-Fiction - SF technologique - Cyberpunk - Rococopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (26,'Roman - Science-Fiction - SF technologique - Cyberpunk - Nowpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (27,'Roman - Science-Fiction - SF technologique - Cyberpunk - Steelpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (28,'Roman - Science-Fiction - SF technologique - Cyberpunk - Raypunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (29,'Roman - Science-Fiction - SF technologique - Cyberpunk - Dreampunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (30,'Roman - Science-Fiction - SF technologique - Cyberpunk - Elfpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (31,'Roman - Science-Fiction - SF technologique - Cyberpunk - Ecopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (32,'Roman - Science-Fiction - SF technologique - Cyberpunk - Clockpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (33,'Roman - Science-Fiction - SF technologique - Cyberpunk - Atompunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (34,'Roman - Science-Fiction - SF technologique - Cyberpunk - Mythpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (35,'Roman - Science-Fiction - SF technologique - Cyberpunk - Stonepunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (36,'Roman - Science-Fiction - SF technologique - Cyberpunk - Steampunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (37,'Roman - Science-Fiction - SF technologique - Cyberpunk - Solarpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (38,'Roman - Science-Fiction - SF technologique - Space Opera - Space Opera militaire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (39,'Roman - Science-Fiction - SF technologique - Space Opera - Space Western',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (40,'Roman - Science-Fiction - SF technologique - Space Opera - Xénofiction',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (41,'Roman - Science-Fiction - SF technologique - apocalyptique et post-apocalyptique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (42,'Roman - Science-Fiction - SF technologique - Planetary Romance et Sword and Planet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (43,'Roman - Science-Fiction - SF technologique - Voyage dans le temps',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (44,'Roman - Science-Fiction - SF technologique - New Wave',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (45,'Roman - Science-Fiction - SF technologique - Edisonade',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (46,'Roman - Science-Fiction - SF politique - Utopie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (47,'Roman - Science-Fiction - SF politique - Dystopie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (48,'Roman - Fantasy - High Fantasy ou Fantasy épique - Sword and Sorcery',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (49,'Roman - Fantasy - High Fantasy ou Fantasy épique - Dark Fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (50,'Roman - Fantasy - Low Fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (51,'Roman - Fantasy - Réalisme magique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (52,'Roman - Fantasy - Fantasy contemporaine - Urban Fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (53,'Roman - Fantasy - Fantasy contemporaine - Bangsian Fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (54,'Roman - Roman d''aventures',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (55,'Roman - Roman d''apprentissage',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (56,'Roman - Roman-feuilleton',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (57,'Roman - Roman pour adolescents',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (58,'Roman - Horreur - Roman gothique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (59,'Roman - Roman d''action',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (60,'Roman - Roman d''espionnage',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (61,'Roman - Thriller - Thriller à mystère',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (62,'Roman - Thriller - Thriller psychologique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (63,'Roman - Thriller - Thriller d''espionnage',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (64,'Roman - Thriller - Thriller noir',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (65,'Roman - Thriller - Thriller d''action - Pulp - Polar',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (66,'Roman - Thriller - Techno-thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (67,'Roman - Thriller - Thriller judiciaire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (68,'Roman - Thriller - Thriller politique - Thriller complotiste',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (69,'Roman - Policier - Policier judiciaire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (70,'Roman - Policier - Policier médical',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (71,'Roman - Policier - Énigme de la chambre close',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (72,'Roman - Noir - Noir urbain',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (73,'Roman - Hard Boiled',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (74,'Roman - Soft Boiled',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (75,'Roman - Roman policier - Roman de détective',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (76,'Roman - Roman sentimental',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (77,'Roman - Érotique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (78,'Roman - Psychologique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (79,'Roman - Humoristique - Humour noir',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (80,'Roman - Humoristique - Satire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (81,'Roman - Humoristique - Parodie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (82,'Roman - Roman de société',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (83,'Roman - Roman épistolaire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (84,'Nouvelle - mêmes sous-genres que le roman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (85,'Conte',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (86,'Fable en prose',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (87,'Historiographie - Monographie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (88,'Historiographie - Annales',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (89,'Historiographie - Chronique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (90,'Historiographie - Histoire universelle',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (91,'Biographie - Autobiographie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (92,'Biographie - Mémoires',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (93,'Journal intime',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT IGNORE INTO `generi` VALUES (94,'Dialogue',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (95,'Traité',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (96,'Essai',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (97,'Pamphlet - Libelle',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (98,'Aphorisme',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (99,'Apologie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (100,'Parabole',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (101,'Manifeste',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (102,'Emblématique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (103,'Lettre en prose - privée',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (104,'Lettre en prose - publique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (105,'Arétalogie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (106,'Hagiographie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (107,'Biographie kérygmatique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (108,'Roman philosophique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (109,'Roman policier',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT IGNORE INTO `generi` VALUES (110,'Éloquence - Discours de cérémonie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT IGNORE INTO `generi` VALUES (111,'Éloquence - Discours judiciaire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT IGNORE INTO `generi` VALUES (112,'Éloquence - Discours délibératif',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT IGNORE INTO `generi` VALUES (113,'Épopée - historique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (114,'Épopée - mythologique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (115,'Épopée - populaire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (116,'Épopée - chevaleresque',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (117,'Épopée - courte',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (118,'Épyllion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (119,'Poème comico-héroïque - court',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT IGNORE INTO `generi` VALUES (120,'Poème didactico-allégorique - court',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT IGNORE INTO `generi` VALUES (121,'Poème didactique - court',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT IGNORE INTO `generi` VALUES (122,'Poème de sagesse - court',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT IGNORE INTO `generi` VALUES (123,'Prophétie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT IGNORE INTO `generi` VALUES (124,'Fable en vers',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT IGNORE INTO `generi` VALUES (125,'Épître philosophique en vers',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT IGNORE INTO `generi` VALUES (126,'Lyrique monodique - Élégie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (127,'Lyrique monodique - Iambe - Kinaïdion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (128,'Lyrique monodique - Iambe - Méliambe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (129,'Lyrique chorale - Dithyrambe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (130,'Lyrique chorale - Enkomion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (131,'Lyrique chorale - Épicède',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (132,'Lyrique chorale - Épinicée',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (133,'Lyrique chorale - Épithalame',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (134,'Lyrique chorale - Hyménée',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (135,'Lyrique chorale - Hymne',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (136,'Lyrique chorale - Hyporckhème',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (137,'Lyrique chorale - Nome',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (138,'Lyrique chorale - Parthénée',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (139,'Lyrique chorale - Péan',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (140,'Lyrique chorale - Prosodion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (141,'Lyrique chorale - Skolion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (142,'Lyrique chorale - Thrène',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (143,'Prière',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (144,'Lauda',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (145,'Poésie bucolique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (146,'Satire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (147,'Sonnet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (148,'Canzone - pétrarquienne',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (149,'Canzone - forme libre',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (150,'Capitolo (chapitre poétique)',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (151,'Poème lyrique (Carmen)',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (152,'Ode',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (153,'Madrigal',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (154,'Ballade',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (155,'Court poème lyrique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (156,'Centon',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (157,'Vers libre',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (158,'Calligramme',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (159,'Épître lyrique',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT IGNORE INTO `generi` VALUES (160,'Tragédie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (161,'Comédie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (162,'Drame',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (163,'Mélodrame',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (164,'Commedia dell''arte',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (165,'Farce',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (166,'Sketch',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (167,'Prosémime',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT IGNORE INTO `generi` VALUES (168,'Opéra - Opéra seria',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (169,'Opéra - Opéra bouffe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (170,'Opéra - Opérette',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (171,'Opéra - Farce',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (172,'Opéra - Zarzuela',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (173,'Opéra - Intermezzi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (174,'Ballet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (175,'Pantomime',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (176,'Mime lyrique - Mimiambe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (177,'Mime lyrique - Hilarotragédie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (178,'Mime lyrique - Magodie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (179,'Mime lyrique - Comédie musicale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (180,'Drame musical',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT IGNORE INTO `generi` VALUES (181,'Oratorio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('cms', 'events_page_enabled', '1', 'Activer ou désactiver la page événements dans le frontend')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('system', 'catalogue_mode', '0', 'Mode catalogue uniquement - désactive les emprunts, réservations et liste de souhaits')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'pickup_expiry_days', '3', 'Jours pour récupérer un emprunt approuvé avant expiration')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), description = VALUES(description), updated_at = NOW();

-- ============================================================================
-- System Settings - Complete default configuration
-- These replace the old storage/settings.json file
-- ============================================================================

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`, `updated_at`) VALUES
-- App settings
('app', 'name', 'Pinakes', 'Nom de l''application', NOW()),
('app', 'logo_path', '', 'Chemin vers le logo de l''application', NOW()),
('app', 'footer_description', 'Votre système Pinakes pour cataloguer, gérer et partager votre collection de livres.', 'Description du pied de page', NOW()),
('app', 'locale', 'fr_FR', 'Paramètre de langue par défaut de l''application', NOW()),
('app', 'social_facebook', '', 'URL du profil Facebook', NOW()),
('app', 'social_twitter', '', 'URL du profil Twitter', NOW()),
('app', 'social_instagram', '', 'URL du profil Instagram', NOW()),
('app', 'social_linkedin', '', 'URL du profil LinkedIn', NOW()),
('app', 'social_bluesky', '', 'URL du profil Bluesky', NOW()),

-- Email settings are configured by user in installer step 6
-- No default values here to avoid overwriting user choices

-- Registration settings
('registration', 'require_admin_approval', '1', 'Approbation administrateur requise pour les nouvelles inscriptions', NOW()),

-- Contacts page settings
('contacts', 'page_title', 'Contactez-nous', 'Titre de la page de contact', NOW()),
('contacts', 'page_content', '<p>Contactez-nous pour toute information.</p>', 'Contenu de la page de contact', NOW()),
('contacts', 'contact_email', '', 'Adresse e-mail de contact', NOW()),
('contacts', 'contact_phone', '', 'Numéro de téléphone de contact', NOW()),
('contacts', 'google_maps_embed', '', 'Code d''intégration Google Maps', NOW()),
('contacts', 'privacy_text', 'Vos données sont protégées conformément à notre politique de confidentialité.', 'Texte de la notice de confidentialité', NOW()),
('contacts', 'recaptcha_site_key', '', 'Clé de site reCAPTCHA', NOW()),
('contacts', 'recaptcha_secret_key', '', 'Clé secrète reCAPTCHA', NOW()),
('contacts', 'notification_email', '', 'Adresse e-mail pour les soumissions du formulaire de contact', NOW()),

-- Privacy page settings
('privacy', 'page_title', 'Politique de confidentialité', 'Titre de la page de politique de confidentialité', NOW()),
('privacy', 'page_content', '<p>Votre vie privée est importante pour nous.</p>', 'Contenu de la page de politique de confidentialité', NOW()),
('privacy', 'cookie_banner_enabled', '1', 'Activer la bannière de consentement aux cookies', NOW()),
('privacy', 'cookie_banner_language', 'fr', 'Langue de la bannière de cookies', NOW()),
('privacy', 'cookie_banner_country', 'fr', 'Pays de la bannière de cookies', NOW()),
('privacy', 'cookie_statement_link', '', 'Lien vers la déclaration de cookies', NOW()),
('privacy', 'cookie_technologies_link', '', 'Lien vers la page des technologies de cookies', NOW()),
('privacy', 'cookie_policy_content', '', 'Contenu de la politique de cookies', NOW()),

-- Cookie banner settings
('cookie_banner', 'banner_description', '<p>Nous utilisons des cookies pour améliorer votre expérience. En continuant à naviguer sur ce site, vous acceptez notre utilisation des cookies.</p>', 'Description de la bannière de cookies', NOW()),
('cookie_banner', 'accept_all_text', 'Tout accepter', 'Texte du bouton « Tout accepter »', NOW()),
('cookie_banner', 'reject_non_essential_text', 'Refuser les non essentiels', 'Texte du bouton « Refuser les non essentiels »', NOW()),
('cookie_banner', 'preferences_button_text', 'Préférences', 'Texte du bouton « Préférences »', NOW()),
('cookie_banner', 'save_selected_text', 'Accepter la sélection', 'Texte du bouton « Enregistrer la sélection »', NOW()),
('cookie_banner', 'preferences_title', 'Personnaliser vos préférences en matière de cookies', 'Titre de la fenêtre de préférences', NOW()),
('cookie_banner', 'preferences_description', '<p>Nous respectons votre droit à la vie privée. Vous pouvez choisir de ne pas autoriser certains types de cookies. Vos préférences s''appliqueront à l''ensemble du site web.</p>', 'Description de la fenêtre de préférences', NOW()),
('cookie_banner', 'cookie_essential_name', 'Cookies essentiels', 'Nom des cookies essentiels', NOW()),
('cookie_banner', 'cookie_essential_description', 'Ces cookies sont nécessaires au fonctionnement du site et ne peuvent pas être désactivés.', 'Description des cookies essentiels', NOW()),
('cookie_banner', 'show_analytics', '1', 'Afficher l''option des cookies analytiques', NOW()),
('cookie_banner', 'cookie_analytics_name', 'Cookies analytiques', 'Nom des cookies analytiques', NOW()),
('cookie_banner', 'cookie_analytics_description', 'Ces cookies nous aident à comprendre comment les visiteurs interagissent avec le site web.', 'Description des cookies analytiques', NOW()),
('cookie_banner', 'show_marketing', '1', 'Afficher l''option des cookies marketing', NOW()),
('cookie_banner', 'cookie_marketing_name', 'Cookies marketing', 'Nom des cookies marketing', NOW()),
('cookie_banner', 'cookie_marketing_description', 'Ces cookies sont utilisés pour diffuser des publicités personnalisées.', 'Description des cookies marketing', NOW()),

-- Advanced settings
('advanced', 'custom_js_essential', '', 'JavaScript personnalisé pour les cookies essentiels', NOW()),
('advanced', 'custom_js_analytics', '', 'JavaScript personnalisé pour les cookies analytiques', NOW()),
('advanced', 'custom_js_marketing', '', 'JavaScript personnalisé pour les cookies marketing', NOW()),
('advanced', 'custom_header_css', '', 'CSS personnalisé pour l''en-tête', NOW()),
('advanced', 'custom_header_js', '', 'JavaScript personnalisé pour l''en-tête', NOW()),
('advanced', 'days_before_expiry_warning', '3', 'Jours avant l''avertissement d''expiration de la carte', NOW()),
('advanced', 'sitemap_last_generated_at', '', 'Horodatage de la dernière génération du plan du site', NOW()),
('advanced', 'sitemap_last_generated_total', '0', 'Nombre total d''URL dans le dernier plan du site généré', NOW()),
('advanced', 'api_enabled', '0', 'Activer l''accès à l''API', NOW()),

-- Label printing settings
('label', 'width', '25', 'Largeur de l''étiquette en mm', NOW()),
('label', 'height', '38', 'Hauteur de l''étiquette en mm', NOW()),
('label', 'format_name', '25x38mm (Standard)', 'Nom du format d''étiquette', NOW()),

-- API settings
('api', 'enabled', '0', 'Activer l''API globalement', NOW()),

-- Social sharing settings
('sharing', 'enabled_providers', 'facebook,x,whatsapp,email', 'Fournisseurs de partage social activés sur la page de détail du livre', NOW())
ON DUPLICATE KEY UPDATE
    setting_value = VALUES(setting_value),
    description = VALUES(description),
    updated_at = NOW();


-- CMS Pages - French
INSERT IGNORE INTO `cms_pages` VALUES (1,'about-us','fr_FR','À propos de nous','<h2>Bienvenue sur Pinakes</h2>\n<p>Pinakes est un système de gestion de bibliothèque moderne, intuitif et entièrement gratuit. Il a été conçu pour simplifier la catalogisation des livres, la gestion des emprunts et l''administration de toute bibliothèque, quelle que soit sa taille.</p>\n\n<h3>🎯 Notre mission</h3>\n<p>Rendre la gestion de bibliothèque accessible à tous, sans frais de licence ni restrictions. Pinakes est 100 % Open Source, libre et gratuit pour tous.</p>\n\n<h3>✨ Fonctionnalités principales</h3>\n<ul>\n    <li><strong>Catalogisation intelligente :</strong> Import automatique des données via ISBN, organisation par catégories, auteurs et classifications personnalisées</li>\n    <li><strong>Gestion des emprunts :</strong> Système complet de gestion des prêts, délais, renouvellements et retours</li>\n    <li><strong>Notifications automatiques :</strong> Rappels par e-mail pour les échéances et la communication avec les utilisateurs</li>\n    <li><strong>Interface moderne :</strong> Design responsive, optimisé pour bureau, tablette et smartphone</li>\n    <li><strong>100 % Open Source :</strong> Code libre, personnalisable et sans coûts cachés</li>\n</ul>\n\n<h3>🚀 Pourquoi choisir Pinakes ?</h3>\n<p>Pinakes est né du besoin d''un outil professionnel, fiable et gratuit pour gérer les bibliothèques scolaires, associatives et les collections privées. Pas besoin d''être expert en informatique : l''interface intuitive permet à chacun de démarrer immédiatement.</p>\n\n<h3>📖 Commencer maintenant</h3>\n<p>Personnalisez cette page avec des informations sur votre bibliothèque, votre équipe et vos services. Accédez au panneau d''administration (CMS &gt; Pages) pour modifier ce contenu et le rendre unique.</p>\n\n<p><em>Il s''agit d''un contenu d''exemple. Personnalisez-le pour raconter l''histoire de votre bibliothèque !</em></p>',NULL,NULL,1,'2025-10-01 10:35:27','2025-10-01 10:35:27');
INSERT IGNORE INTO `cms_pages` VALUES (2,'privacy-policy','fr_FR','Politique de confidentialité','<h2>Politique de confidentialité</h2>\n<p>Il s''agit d''une page d''espace réservé pour la politique de confidentialité. Adaptez ce contenu conformément à la réglementation en vigueur (RGPD) et aux exigences spécifiques de votre bibliothèque.</p>\n\n<h3>1. Responsable du traitement</h3>\n<p>[Indiquez ici les coordonnées du responsable du traitement : nom, adresse, e-mail, téléphone]</p>\n\n<h3>2. Données collectées</h3>\n<p>Les données personnelles collectées via ce système comprennent :</p>\n<ul>\n    <li>Données personnelles (nom, prénom, date de naissance)</li>\n    <li>Coordonnées (e-mail, téléphone, adresse)</li>\n    <li>Données relatives aux emprunts effectués</li>\n</ul>\n\n<h3>3. Finalité du traitement</h3>\n<p>Les données sont traitées exclusivement pour :</p>\n<ul>\n    <li>Gestion de l''inscription des utilisateurs</li>\n    <li>Gestion des emprunts de la bibliothèque</li>\n    <li>Envoi de communications relatives aux emprunts (échéances, renouvellements)</li>\n</ul>\n\n<h3>4. Droits des personnes concernées</h3>\n<p>Les personnes concernées ont le droit d''accès, de rectification, d''effacement ou de limitation du traitement de leurs données, tel que prévu par le règlement (UE) 2016/679 (RGPD).</p>\n\n<p><strong>IMPORTANT :</strong> Il s''agit d''un modèle. Consultez un expert juridique pour créer une politique de confidentialité conforme à la réglementation en vigueur.</p>\n\n<p><em>Accédez au panneau d''administration (CMS &gt; Pages) pour personnaliser cette page.</em></p>',NULL,NULL,1,'2025-10-01 10:35:27','2025-10-01 10:35:27');

-- Email Templates - French
INSERT IGNORE INTO `email_templates` VALUES (1,'admin_new_registration','fr_FR','👤 Nouvelle demande d''inscription','<h2>Nouvelle demande d''inscription</h2>\n<p>Un nouvel utilisateur a demandé l''accès au système de bibliothèque :</p>\n<p><strong>Données de l''utilisateur :</strong></p>\n<ul>\n    <li>Nom : {{first_name}} {{last_name}}</li>\n    <li>E-mail : {{email}}</li>\n    <li>Numéro de carte : {{card_code}}</li>\n    <li>Date d''inscription : {{registration_date}}</li>\n</ul>\n<p><a href=\"{{admin_users_url}}\" style=\"background-color: #3b82f6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;\">Gérer les utilisateurs</a></p>','E-mail envoyé aux administrateurs lors d''une nouvelle inscription d''utilisateur.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (2,'admin_new_review','fr_FR','⭐ Nouvel avis à approuver','<h2>Nouvel avis à approuver</h2>\n<p>Un nouvel avis a été soumis pour le livre suivant :</p>\n<p><strong>Livre :</strong> {{book_title}}</p>\n<div style=\"background-color: #fff7ed; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #f59e0b;\">\n    <p><strong>Note :</strong> {{stars}} étoiles ⭐</p>\n    <p><strong>Utilisateur :</strong> {{user_name}} ({{user_email}})</p>\n    <p><strong>Date de l''avis :</strong> {{review_date}}</p>\n    <p><strong>Titre :</strong> {{review_title}}</p>\n    <p><strong>Description :</strong></p>\n    <p style=\"white-space: pre-line;\">{{review_description}}</p>\n</div>\n<p style=\"text-align: center;\">\n    <a href=\"{{approval_link}}\" style=\"background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">Gérer l''avis</a>\n</p>\n<p><em>Pour approuver ou refuser cet avis, accédez au panneau d''administration.</em></p>','Envoyé aux administrateurs lorsqu''un nouvel avis est soumis pour approbation.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (3,'loan_approved','fr_FR','✅ Votre demande d''emprunt a été approuvée !','<h2>Votre demande d''emprunt a été approuvée !</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Nous avons le plaisir de vous informer que votre demande d''emprunt a été <strong>approuvée</strong> !</p>\n<p><strong>Détails de l''emprunt :</strong></p>\n<ul>\n    <li>Livre : {{book_title}}</li>\n    <li>Date de début : {{start_date}}</li>\n    <li>Date de retour : {{end_date}}</li>\n    <li>Durée : {{loan_days}} jours</li>\n</ul>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;\">\n    <p><strong>📦 Retrait du livre</strong></p>\n    <p>{{pickup_instructions}}</p>\n</div>\n<p><strong>Important :</strong> Veuillez retourner le livre avant la date d''échéance. Vous recevrez un rappel quelques jours avant l''expiration.</p>\n<p>Bonne lecture !</p>','Envoyé à l''utilisateur lorsqu''un administrateur approuve une demande d''emprunt.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (4,'loan_rejected','fr_FR','❌ Votre demande d''emprunt n''a pas été approuvée','<h2>Votre demande d''emprunt n''a pas été approuvée</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Nous avons le regret de vous informer que votre demande d''emprunt pour le livre <strong>\"{{book_title}}\"</strong> n''a pas été approuvée.</p>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>Motif :</strong></p>\n    <p>{{rejection_reason}}</p>\n</div>\n<p>Si vous avez des questions ou avez besoin d''informations complémentaires, n''hésitez pas à nous contacter.</p>\n<p>Cordialement,<br>L''équipe de la bibliothèque</p>','Envoyé à l''utilisateur lorsqu''un administrateur refuse une demande d''emprunt.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (5,'loan_expiring_warning','fr_FR','⚠️ Votre emprunt expire bientôt','<h2>Rappel d''échéance d''emprunt</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Nous vous rappelons que votre emprunt expire bientôt :</p>\n<p><strong>Détails de l''emprunt :</strong></p>\n<ul>\n    <li>Livre : {{book_title}}</li>\n    <li>Date d''échéance : {{due_date}}</li>\n    <li>Jours restants : {{days_remaining}}</li>\n</ul>\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏰ Action requise</strong></p>\n    <p>Pour éviter des pénalités, veuillez retourner le livre avant la date d''échéance ou contacter la bibliothèque pour un éventuel renouvellement.</p>\n</div>\n<p>Merci pour votre coopération !</p>','E-mail envoyé à l''utilisateur 3 jours avant l''expiration de l''emprunt.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (6,'loan_overdue_admin','fr_FR','Emprunt #{{loan_id}} en retard','<h2>Emprunt en retard</h2>\n<p>L''emprunt <strong>#{{loan_id}}</strong> a atteint le statut <strong>en retard</strong>.</p>\n<ul>\n  <li><strong>Livre :</strong> {{book_title}}</li>\n  <li><strong>Utilisateur :</strong> {{user_name}} ({{user_email}})</li>\n  <li><strong>Date d''emprunt :</strong> {{loan_date}}</li>\n  <li><strong>Date de retour :</strong> {{due_date}}</li>\n</ul>\n<p>Veuillez contacter l''utilisateur pour demander le retour du livre.</p>','Notifie les administrateurs lorsqu''un emprunt est en retard.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (7,'loan_overdue_notification','fr_FR','🚨 Emprunt en retard - Action requise','<h2>Emprunt en retard</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Votre emprunt est en retard et doit être retourné immédiatement :</p>\n<p><strong>Détails de l''emprunt :</strong></p>\n<ul>\n    <li>Livre : {{book_title}}</li>\n    <li>Date de retour : {{due_date}}</li>\n    <li>En retard depuis : {{days_overdue}} jours</li>\n</ul>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>🚨 Action urgente requise</strong></p>\n    <p>Le livre doit être retourné immédiatement. Les retards peuvent entraîner des pénalités et une suspension du service.</p>\n</div>\n<p>Veuillez contacter la bibliothèque dès que possible pour résoudre cette situation.</p>','E-mail envoyé à l''utilisateur lorsque l''emprunt est en retard.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (8,'loan_request_notification','fr_FR','📚 Nouvelle demande d''emprunt','<h2>Nouvelle demande d''emprunt</h2>\n<p>Une nouvelle demande d''emprunt a été soumise :</p>\n<p><strong>Détails :</strong></p>\n<ul>\n    <li>Livre : {{book_title}}</li>\n    <li>Utilisateur : {{user_name}} ({{user_email}})</li>\n    <li>Date de début souhaitée : {{start_date}}</li>\n    <li>Date de fin souhaitée : {{end_date}}</li>\n    <li>Date de la demande : {{request_date}}</li>\n</ul>\n<p><a href=\"{{approve_url}}\" style=\"background-color: #10b981; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;\">Gérer la demande</a></p>','E-mail envoyé aux administrateurs lorsqu''un utilisateur demande un emprunt.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (9,'user_account_approved','fr_FR','Compte approuvé - Bienvenue dans la bibliothèque !','<h2>Votre compte a été approuvé !</h2>\n<p>Bonjour {{first_name}} {{last_name}},</p>\n<p>Nous avons le plaisir de vous informer que votre compte a été approuvé par un administrateur.</p>\n<p>Vous pouvez maintenant vous connecter et réserver des livres !</p>\n<p><strong>Vos informations de compte :</strong></p>\n<ul>\n    <li>E-mail : {{email}}</li>\n    <li>Numéro de carte : {{card_code}}</li>\n</ul>\n<p><a href=\"{{login_url}}\" style=\"background-color: #3b82f6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;\">Se connecter maintenant</a></p>\n<p>Bienvenue dans notre bibliothèque numérique !</p>','E-mail envoyé lorsqu''un administrateur approuve le compte directement sans exiger la vérification par e-mail.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (10,'user_activation_with_verification','fr_FR','Activer votre compte - Confirmer votre e-mail','<h2>Votre compte a été approuvé !</h2>\n<p>Bonjour {{first_name}} {{last_name}},</p>\n<p>Nous avons le plaisir de vous informer que votre compte a été approuvé par un administrateur.</p>\n<p>📧 <strong>Confirmez votre adresse e-mail</strong></p>\n<p>Pour finaliser l''activation, cliquez sur le bouton ci-dessous pour confirmer votre adresse e-mail :</p>\n<p style=\"text-align: center; margin: 30px 0;\">\n    <a href=\"{{verification_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block;\">✅ Confirmer l''e-mail</a>\n</p>\n<p><strong>Vos informations de compte :</strong></p>\n<ul>\n    <li>E-mail : {{email}}</li>\n    <li>Numéro de carte : {{card_code}}</li>\n</ul>\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏰ Important</strong></p>\n    <p>Le lien de confirmation est valide pendant 7 jours. Après confirmation, vous pourrez vous connecter et réserver des livres.</p>\n</div>\n<p>Si vous n''avez pas demandé cette inscription, vous pouvez ignorer cet e-mail.</p>','E-mail envoyé lorsqu''un administrateur approuve le compte et exige une vérification par e-mail.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (11,'user_registration_pending','fr_FR','Inscription reçue - Approbation en attente','<h2>Bienvenue {{first_name}} {{last_name}} !</h2>\n<p>Votre demande d''inscription a été reçue avec succès.</p>\n<p><strong>Informations du compte :</strong></p>\n<ul>\n    <li>E-mail : {{email}}</li>\n    <li>Numéro de carte : {{card_code}}</li>\n    <li>Date d''inscription : {{registration_date}}</li>\n</ul>\n{{verify_section}}\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏳ Compte en attente d''approbation</strong></p>\n    <p>Votre compte est en attente d''approbation par un administrateur. Vous recevrez un e-mail de confirmation dès que votre compte sera activé.</p>\n</div>\n<p>Merci d''avoir choisi notre système de bibliothèque !</p>','E-mail envoyé à l''utilisateur après l''inscription lorsque le compte est en attente d''approbation.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (12,'wishlist_book_available','fr_FR','📖 Livre de votre liste de souhaits maintenant disponible !','<h2>Bonne nouvelle !</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Le livre que vous avez ajouté à votre liste de souhaits est maintenant disponible à l''emprunt :</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">{{book_title}}</h3>\n    <p style=\"margin: 5px 0;\"><strong>Auteur :</strong> {{book_author}}</p>\n    <p style=\"margin: 5px 0;\"><strong>ISBN :</strong> {{book_isbn}}</p>\n    <p style=\"margin: 5px 0;\"><strong>Disponible à partir du :</strong> {{availability_date}}</p>\n</div>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>✨ Réservez maintenant !</strong></p>\n    <p>Le livre est maintenant disponible à la réservation. Dépêchez-vous avant que quelqu''un d''autre ne le réserve !</p>\n</div>\n<p style=\"text-align: center;\">\n    <a href=\"{{book_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">📚 Réserver maintenant</a>\n    <a href=\"{{wishlist_url}}\" style=\"background-color: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">❤️ Gérer ma liste de souhaits</a>\n</p>\n<p><em>Ce livre a été automatiquement retiré de votre liste de souhaits.</em></p>','E-mail envoyé lorsqu''un livre de la liste de souhaits devient disponible.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (13,'reservation_book_available','fr_FR','📚 Livre réservé prêt à être récupéré !','<h2>Votre livre est prêt à être récupéré !</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Nous avons le plaisir de vous informer que le livre que vous avez réservé est maintenant disponible et prêt à être récupéré :</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">{{book_title}}</h3>\n    <p style=\"margin: 5px 0;\"><strong>Auteur :</strong> {{book_author}}</p>\n    <p style=\"margin: 5px 0;\"><strong>ISBN :</strong> {{book_isbn}}</p>\n    <p style=\"margin: 5px 0;\"><strong>Période d''emprunt :</strong> {{start_date}} - {{end_date}}</p>\n</div>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;\">\n    <p><strong>📦 Prochaines étapes</strong></p>\n    <p>Rendez-vous à la bibliothèque pour récupérer le livre. Veuillez apporter une pièce d''identité.</p>\n</div>\n<p style=\"text-align: center;\">\n    <a href=\"{{book_url}}\" style=\"background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">📖 Voir le livre</a>\n    <a href=\"{{profile_url}}\" style=\"background-color: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">👤 Mes emprunts</a>\n</p>\n<p><em>Votre réservation a été convertie en emprunt en attente de confirmation de retrait.</em></p>','E-mail envoyé lorsqu''un livre réservé devient disponible et est converti en emprunt.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (14,'user_password_setup','fr_FR','🔐 Configurer votre mot de passe','<h2>Configurer votre mot de passe</h2>\n<p>Bonjour {{first_name}} {{last_name}},</p>\n<p>Votre compte sur <strong>{{app_name}}</strong> a été créé. Pour utiliser le système, vous devez configurer votre mot de passe.</p>\n<div style=\"background-color: #f0f9ff; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #3b82f6;\">\n    <p><strong>🔑 Configurer votre compte</strong></p>\n    <p>Cliquez sur le bouton ci-dessous pour définir votre mot de passe :</p>\n</div>\n<p style=\"text-align: center; margin: 30px 0;\">\n    <a href=\"{{reset_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block;\">🔐 Définir mon mot de passe</a>\n</p>\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏰ Important</strong></p>\n    <p>Ce lien est valide pendant 24 heures. S''il expire, contactez un administrateur pour en obtenir un nouveau.</p>\n</div>\n<p>Si vous n''avez pas demandé cet e-mail, vous pouvez l''ignorer.</p>','E-mail envoyé aux nouveaux utilisateurs pour configurer leur mot de passe.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (15,'admin_invitation','fr_FR','🎉 Invitation d''administrateur','<h2>Bienvenue dans l''équipe !</h2>\n<p>Bonjour {{first_name}} {{last_name}},</p>\n<p>Vous avez été invité(e) en tant qu''administrateur sur <strong>{{app_name}}</strong>.</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">Votre accès</h3>\n    <p>En tant qu''administrateur, vous avez accès à :</p>\n    <ul>\n        <li>Gestion du catalogue de livres</li>\n        <li>Gestion des utilisateurs et des emprunts</li>\n        <li>Paramètres du système</li>\n        <li>Rapports et statistiques</li>\n    </ul>\n</div>\n<p><strong>Pour commencer :</strong></p>\n<ol>\n    <li>Définissez votre mot de passe en cliquant sur le bouton ci-dessous</li>\n    <li>Accédez au tableau de bord administrateur</li>\n</ol>\n<p style=\"text-align: center; margin: 30px 0;\">\n    <a href=\"{{reset_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block; margin: 10px;\">🔐 Définir mon mot de passe</a>\n    <a href=\"{{dashboard_url}}\" style=\"background-color: #3b82f6; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block; margin: 10px;\">📊 Tableau de bord</a>\n</p>\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏰ Important</strong></p>\n    <p>Le lien de création de mot de passe est valide pendant 24 heures.</p>\n</div>\n<p>Bienvenue dans l''équipe !</p>','E-mail envoyé lorsqu''un utilisateur est invité en tant qu''administrateur.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (16,'loan_pickup_ready','fr_FR','📦 Livre prêt à être récupéré !','<h2>Livre prêt à être récupéré !</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Nous avons le plaisir de vous informer que votre livre est prêt à être récupéré !</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">{{book_title}}</h3>\n    <p style=\"margin: 5px 0;\"><strong>Période d''emprunt :</strong> {{start_date}} - {{end_date}}</p>\n    <p style=\"margin: 5px 0;\"><strong>Date limite de retrait :</strong> {{pickup_deadline}}</p>\n</div>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;\">\n    <p><strong>📦 Retrait</strong></p>\n    <p>{{pickup_instructions}}</p>\n</div>\n<p>Bonne lecture !</p>','Envoyé lorsqu''un emprunt a été approuvé et que le livre est prêt à être récupéré.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (17,'loan_pickup_expired','fr_FR','⏰ Délai de retrait expiré','<h2>Délai de retrait expiré</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Malheureusement, vous n''avez pas récupéré le livre dans le délai imparti.</p>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>Livre :</strong> {{book_title}}</p>\n    <p><strong>Date limite de retrait :</strong> {{pickup_deadline}}</p>\n</div>\n<p>L''emprunt a été automatiquement annulé et le livre est maintenant disponible pour d''autres utilisateurs.</p>\n<p>Si vous souhaitez toujours emprunter ce livre, veuillez soumettre une nouvelle demande.</p>\n<p>Cordialement,<br>L''équipe de la bibliothèque</p>','Envoyé lorsque le délai de retrait expire et que l''emprunt est automatiquement annulé.',1,NULL,NULL);
INSERT IGNORE INTO `email_templates` VALUES (18,'loan_pickup_cancelled','fr_FR','❌ Retrait annulé','<h2>Retrait annulé</h2>\n<p>Bonjour {{user_name}},</p>\n<p>Nous vous informons que le retrait du livre suivant a été annulé :</p>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>Livre :</strong> {{book_title}}</p>\n    <p><strong>Motif :</strong> {{reason}}</p>\n</div>\n<p>Le livre est maintenant disponible pour d''autres utilisateurs. Si vous souhaitez toujours l''emprunter, veuillez soumettre une nouvelle demande.</p>\n<p>Cordialement,<br>L''équipe de la bibliothèque</p>','Envoyé lorsqu''un retrait est annulé par l''administrateur.',1,NULL,NULL);

-- Languages (French as default)
-- FIX F023: total_keys/translated_keys/completion_percentage updated to real
-- JSON key counts (jq '[paths(scalars)] | length'): it_IT=493, en_US=4653,
-- de_DE=4653, fr_FR=4993. Previous values (2015/4009/4080) were stale and
-- inconsistent with migrate_0.7.5.sql (which used 4145). Fresh installs now
-- match the actual translation file contents.
INSERT INTO `languages` (`code`, `name`, `native_name`, `flag_emoji`, `is_default`, `is_active`, `translation_file`, `total_keys`, `translated_keys`, `completion_percentage`) VALUES
('it_IT', 'Italian', 'Italiano', '🇮🇹', 0, 1, NULL, 493, 493, 100.00),
('en_US', 'English', 'English', '🇬🇧', 0, 1, 'locale/en_US.json', 4653, 4653, 100.00),
('de_DE', 'German', 'Deutsch', '🇩🇪', 0, 1, 'locale/de_DE.json', 4653, 4653, 100.00),
('fr_FR', 'French', 'Français', '🇫🇷', 1, 1, 'locale/fr_FR.json', 4993, 4993, 100.00)
ON DUPLICATE KEY UPDATE name = VALUES(name), native_name = VALUES(native_name), flag_emoji = VALUES(flag_emoji), translation_file = VALUES(translation_file), total_keys = VALUES(total_keys), translated_keys = VALUES(translated_keys), completion_percentage = VALUES(completion_percentage), is_active = VALUES(is_active), is_default = VALUES(is_default);

-- Home Content (French)
INSERT INTO `home_content` (section_key, title, subtitle, content, button_text, button_link, is_active, display_order, created_at, updated_at) VALUES
('hero', 'Votre bibliothèque numérique', 'Découvrez, réservez et gérez votre collection de livres', NULL, 'Découvrir le catalogue', '/catalogue', 1, -2, NOW(), NOW()),
('features_title', 'Pourquoi choisir Pinakes', 'Une expérience bibliothécaire moderne et intuitive, toujours à portée de main', NULL, NULL, NULL, 1, 0, NOW(), NOW()),
('feature_1', 'Gestion simplifiée', 'Cataloguez vos livres, gérez les emprunts et les retours avec une interface intuitive et rapide', 'fas fa-tasks', NULL, NULL, 1, 1, NOW(), NOW()),
('feature_2', 'Catalogisation complète', 'Importez des données via ISBN, organisez par catégories, créez des étiquettes et suivez chaque exemplaire physique', 'fas fa-book', NULL, NULL, 1, 2, NOW(), NOW()),
('feature_3', 'Système de gestion des emprunts', 'Gérez les prêts, les échéances, les renouvellements et les notifications automatiques par e-mail pour les utilisateurs et le personnel', 'fas fa-exchange-alt', NULL, NULL, 1, 3, NOW(), NOW()),
('feature_4', 'Open Source & Gratuit', 'Logiciel 100 % libre, sans frais de licence. Personnalisez et contribuez au projet Pinakes', 'fas fa-code-branch', NULL, NULL, 1, 4, NOW(), NOW()),
('text_content', 'Πίνακες (Pinakes) - « Les Tables »', NULL, '<p>Le nom <strong>Pinakes</strong> vient du grec ancien <em>πίνακες</em> (pinakes), signifiant « tables » ou « tableaux ». Il rend hommage à <strong>Callimaque de Cyrène</strong> (305-240 av. J.-C.), qui réalisa vers 245 av. J.-C. le premier catalogue bibliothécaire systématique de l''histoire pour la Bibliothèque d''Alexandrie : les <em>Πίνακες τῶν ἐν πάσῃ παιδείᾳ διαλαμψάντων καὶ ὧν συνέγραψαν</em> (« Tables de ceux qui se sont illustrés dans tous les domaines du savoir et de leurs œuvres »).</p><p>Cette œuvre monumentale, composée de 120 rouleaux, organisait systématiquement plus de 120 000 rouleaux de papyrus de la Bibliothèque. Bien que les <em>Pinakes</em> originaux soient perdus, leur méthode de catalogisation a profondément influencé la bibliothéconomie moderne.</p><p>Ce projet perpétue cette tradition vieille de <strong>2 268 ans</strong>, apportant les mêmes principes d''organisation et d''accessibilité du savoir à l''ère numérique.</p>', NULL, NULL, 1, 4, NOW(), NOW()),
('latest_books_title', 'Dernières acquisitions', 'Découvrez les derniers ajouts au catalogue', NULL, NULL, NULL, 1, 5, NOW(), NOW()),
('genre_carousel', 'Découvrez les genres principaux', 'Explorez nos racines thématiques et laissez-vous inspirer par les titres disponibles.', NULL, NULL, NULL, 1, 6, NOW(), NOW()),
('events', 'Événements à venir', 'Participez à nos prochaines rencontres', NULL, NULL, NULL, 1, 7, NOW(), NOW()),
('cta', 'Prêt à commencer ?', 'Inscrivez-vous maintenant et commencez à explorer notre catalogue', NULL, 'S''inscrire maintenant', '/inscription', 1, 8, NOW(), NOW())
ON DUPLICATE KEY UPDATE title = VALUES(title), subtitle = VALUES(subtitle), content = VALUES(content), button_text = VALUES(button_text), button_link = VALUES(button_link), is_active = VALUES(is_active), display_order = VALUES(display_order), updated_at = NOW();

-- Themes (French descriptions)
INSERT IGNORE INTO `themes` (`name`, `slug`, `version`, `author`, `description`, `active`, `settings`) VALUES
('Pinakes Classic', 'default', '1.0.0', 'Pinakes Team', 'Thème standard avec les couleurs magenta originales de Pinakes', 1, '{"colors": {"primary": "#d70161", "secondary": "#111827", "button": "#d70262", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Minimal', 'minimal-bw', '1.0.0', 'Pinakes Team', 'Design minimaliste en noir, gris et blanc pour un rendu épuré et élégant', 0, '{"colors": {"primary": "#404040", "secondary": "#000000", "button": "#808080", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Ocean Blue', 'ocean-blue', '1.0.0', 'Pinakes Team', 'Teintes océan modernes et professionnelles pour une interface fraîche', 0, '{"colors": {"primary": "#0284c7", "secondary": "#0c4a6e", "button": "#0ea5e9", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Forest Green', 'forest-green', '1.0.0', 'Pinakes Team', 'Vert émeraude naturel évoquant la sérénité de la nature', 0, '{"colors": {"primary": "#059669", "secondary": "#064e3b", "button": "#10b981", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Sunset Orange', 'sunset-orange', '1.0.0', 'Pinakes Team', 'Orange chaleureux et accueillant, inspiré des couchers de soleil méditerranéens', 0, '{"colors": {"primary": "#ea580c", "secondary": "#7c2d12", "button": "#f97316", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Burgundy', 'burgundy-red', '1.0.0', 'Pinakes Team', 'Bordeaux élégant et raffiné pour un style sophistiqué', 0, '{"colors": {"primary": "#be123c", "secondary": "#881337", "button": "#e11d48", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Teal Professional', 'teal-professional', '1.0.0', 'Pinakes Team', 'Bleu-vert professionnel, parfait pour les environnements institutionnels', 0, '{"colors": {"primary": "#0d9488", "secondary": "#134e4a", "button": "#14b8a6", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Slate Gray', 'slate-gray', '1.0.0', 'Pinakes Team', 'Gris ardoise moderne pour un design neutre et contemporain', 0, '{"colors": {"primary": "#475569", "secondary": "#1e293b", "button": "#64748b", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Coral Warm', 'coral-warm', '1.0.0', 'Pinakes Team', 'Teintes corail chaudes et accueillantes pour une atmosphère chaleureuse', 0, '{"colors": {"primary": "#f43f5e", "secondary": "#9f1239", "button": "#fb7185", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Navy Classic', 'navy-classic', '1.0.0', 'Pinakes Team', 'Bleu marine classique et intemporel pour un style institutionnel', 0, '{"colors": {"primary": "#1e40af", "secondary": "#1e3a8a", "button": "#3b82f6", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}');

SET FOREIGN_KEY_CHECKS=1;
