-- Initial data for Pinakes
-- Generated by installer

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('cms', 'events_page_enabled', '1', 'Abilita o disabilita la pagina degli eventi nel frontend');

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('system', 'catalogue_mode', '0', 'Modalità solo catalogo - disabilita prestiti, prenotazioni e wishlist');

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'pickup_expiry_days', '3', 'Giorni per ritirare un prestito approvato prima che scada');

INSERT INTO `generi` VALUES (1,'Prosa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT INTO `generi` VALUES (2,'Poesia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT INTO `generi` VALUES (3,'Teatro',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT INTO `generi` VALUES (4,'Narrativa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT INTO `generi` VALUES (5,'Divulgativa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT INTO `generi` VALUES (6,'Eloquenza',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT INTO `generi` VALUES (7,'Epica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT INTO `generi` VALUES (8,'Didascalica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT INTO `generi` VALUES (9,'Lirica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT INTO `generi` VALUES (10,'Teatro di prosa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',3);
INSERT INTO `generi` VALUES (11,'Teatro di musica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',3);
INSERT INTO `generi` VALUES (12,'Romanzo - frammento',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (13,'Romanzo - storico - fantastoria',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (14,'Romanzo - storico - ucronia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (15,'Romanzo - storico - cappa e spada o wuxia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (16,'Romanzo - storico - Peplum o Sword and sandal',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (17,'Romanzo - fantascienza - fantascienza tecnologica - Singularity Fiction',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (18,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - postcyberpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (19,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - biopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (20,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - nanopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (21,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - dieselpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (22,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - decopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (23,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - Swordpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (24,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - sandalpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (25,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - Rococopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (26,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - nowpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (27,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - steelpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (28,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - raypunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (29,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - Dreampunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (30,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - Elfpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (31,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - Ecopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (32,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - clockpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (33,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - atompunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (34,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - mythpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (35,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - stonepunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (36,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - steampunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (37,'Romanzo - fantascienza - fantascienza tecnologica - cyberpunk - solarpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (38,'Romanzo - fantascienza - fantascienza tecnologica - space opera - space opera militare',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (39,'Romanzo - fantascienza - fantascienza tecnologica - space opera - space western',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (40,'Romanzo - fantascienza - fantascienza tecnologica - space opera - xenofiction',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (41,'Romanzo - fantascienza - fantascienza tecnologica - apocalittico e postapocalittico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (42,'Romanzo - fantascienza - fantascienza tecnologica - planetary romance e sword and planet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (43,'Romanzo - fantascienza - fantascienza tecnologica - viaggi nel tempo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (44,'Romanzo - fantascienza - fantascienza tecnologica - new wave',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (45,'Romanzo - fantascienza - fantascienza tecnologica - edisonata',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (46,'Romanzo - fantascienza - fantapolitica - utopia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (47,'Romanzo - fantascienza - fantapolitica - distopia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (48,'Romanzo - fantasy - high fantasy o fantasy epico - sword and sorcery',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (49,'Romanzo - fantasy - high fantasy o fantasy epico - dark fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (50,'Romanzo - fantasy - low fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (51,'Romanzo - fantasy - Realismo magico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (52,'Romanzo - fantasy - fantasy contemporaneo - urban fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (53,'Romanzo - fantasy - fantasy contemporaneo - bangsian fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (54,'Romanzo - romanzo d\'avventura',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (55,'Romanzo - romanzo di formazione',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (56,'Romanzo - romanzo d\'appendice',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (57,'Romanzo - romanzo per ragazzi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (58,'Romanzo - romanzo dell\'orrore - gotico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (59,'Romanzo - romanzo d\'azione',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (60,'Romanzo - Spy story',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (61,'Romanzo - thriller - Mistery Thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (62,'Romanzo - thriller - Thriller psicologico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (63,'Romanzo - thriller - Thriller di spionaggio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (64,'Romanzo - thriller - Noir Thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (65,'Romanzo - thriller - Action Thriller - Pulp - Crime Thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (66,'Romanzo - thriller - Tecnothriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (67,'Romanzo - thriller - legal thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (68,'Romanzo - thriller - Thriller politico - Thriller cospirativo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (69,'Romanzo - giallo - giallo giudiziario',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (70,'Romanzo - giallo - giallo medico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (71,'Romanzo - giallo - Enigma della camera chiusa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (72,'Romanzo - noir - noir metropolitano',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (73,'Romanzo - hard boiled',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (74,'Romanzo - soft boiled',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (75,'Romanzo - poliziesco - Police procedural',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (76,'Romanzo - rosa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (77,'Romanzo - erotico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (78,'Romanzo - psicologico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (79,'Romanzo - umoristico - umorismo nero',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (80,'Romanzo - umoristico - satira',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (81,'Romanzo - umoristico - parodia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (82,'Romanzo - sociale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (83,'Romanzo - epistolare',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (84,'Racconto - stessi sottogeneri del romanzo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (85,'Fiaba',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (86,'Favola in prosa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (87,'Storiografia - monografia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (88,'Storiografia - annali',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (89,'Storiografia - cronaca',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (90,'Storiografia - storia universale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (91,'Biografia - autobiografia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (92,'Biografia - memorialistica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (93,'Diario',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (94,'Dialogo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (95,'Trattato',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (96,'Saggio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (97,'Opuscolo - Libello',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (98,'Aforisma',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (99,'Apologia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (100,'Parabola',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (101,'Manifesto',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (102,'Emblematica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (103,'Epistola in prosa - privata',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (104,'Epistola in prosa - pubblica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (105,'aretalogia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (106,'agiografia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (107,'biografia kerygmatica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (108,'romanzo filosofico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (109,'romanzo d\'inchiesta',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (110,'Oratoria - Oratoria epidittica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT INTO `generi` VALUES (111,'Oratoria - Oratoria giudiziaria',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT INTO `generi` VALUES (112,'Oratoria - Oratoria deliberativa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT INTO `generi` VALUES (113,'Poema epico - storico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (114,'Poema epico - mitologico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (115,'Poema epico - collettivo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (116,'Poema epico - epico-cavalleresco',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (117,'Poema epico - poemetto epico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (118,'Epillio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (119,'Poema eroicomico - poemetto eroicomico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (120,'Poema didattico-allegorico - poemetto didattico-allegorico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (121,'Poema didascalico - poemetto didascalico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (122,'Poema sapienziale - poemetto sapienziale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (123,'Profezia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (124,'favola in versi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (125,'epistola filosofica in versi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (126,'lirica monodica - Elegia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (127,'lirica monodica - Giambo - Cinedio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (128,'lirica monodica - Giambo - Meliambo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (129,'lirica corale - Ditirambo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (130,'lirica corale - Encomio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (131,'lirica corale - Epicedio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (132,'lirica corale - Epinicio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (133,'lirica corale - Epitalamio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (134,'lirica corale - Imeneo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (135,'lirica corale - Inno',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (136,'lirica corale - Iporchema',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (137,'lirica corale - Nomo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (138,'lirica corale - Partenio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (139,'lirica corale - Peana',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (140,'lirica corale - Prosodio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (141,'lirica corale - Scolio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (142,'lirica corale - Treno',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (143,'Preghiera',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (144,'Lauda',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (145,'Poesia bucolica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (146,'Satira',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (147,'Sonetto',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (148,'Canzone - petrarchesca',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (149,'Canzone - libera',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (150,'Capitolo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (151,'Carme',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (152,'Ode',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (153,'Madrigale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (154,'Ballata',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (155,'Poemetto lirico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (156,'Centone',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (157,'Verso libero',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (158,'Calligramma',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (159,'Epistola lirica',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (160,'Tragedia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (161,'Commedia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (162,'Dramma',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (163,'Melodramma',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (164,'Commedia dell\'arte',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (165,'Farsa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (166,'Sketch',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (167,'Mimo prosastico',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (168,'Opera - opera seria',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (169,'Opera - opera buffa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (170,'Opera - operetta',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (171,'Opera - farsa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (172,'Opera - Zarzuela',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (173,'Opera - Intermezzi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (174,'Balletto',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (175,'Pantomima',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (176,'Mimo lirico - mimiambo',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (177,'Mimo lirico - ilarodia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (178,'Mimo lirico - magodia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (179,'Mimo lirico - Musicale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (180,'Dramma musicale',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (181,'Oratorio',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `home_content` (section_key, title, subtitle, content, button_text, button_link, is_active, display_order, created_at, updated_at) VALUES
('hero', 'La Tua Biblioteca Digitale', 'Esplora, prenota e gestisci la tua collezione di libri', NULL, 'Esplora il Catalogo', '/catalogo', 1, -2, NOW(), NOW()),
('features_title', 'Perché Scegliere Pinakes', 'Un\'esperienza di gestione biblioteca moderna, intuitiva e sempre a portata di mano', NULL, NULL, NULL, 1, 0, NOW(), NOW()),
('feature_1', 'Gestione Semplificata', 'Cataloga i tuoi libri, gestisci prestiti e restituzioni con un\'interfaccia intuitiva e veloce', 'fas fa-tasks', NULL, NULL, 1, 1, NOW(), NOW()),
('feature_2', 'Catalogazione Completa', 'Importa dati da ISBN, organizza per categorie, genera etichette e traccia ogni copia fisica', 'fas fa-book', NULL, NULL, 1, 2, NOW(), NOW()),
('feature_3', 'Sistema di Prestiti', 'Gestisci prestiti, scadenze, rinnovi e notifiche automatiche via email per utenti e staff', 'fas fa-exchange-alt', NULL, NULL, 1, 3, NOW(), NOW()),
('feature_4', 'Open Source & Gratuito', 'Software libero al 100%, senza costi di licenza. Personalizza e contribuisci al progetto Pinakes', 'fas fa-code-branch', NULL, NULL, 1, 4, NOW(), NOW()),
('text_content', 'Πίνακες (Pinakes) - "Le Tavole"', NULL, '<p>Il nome <strong>Pinakes</strong> deriva dal greco antico <em>πίνακες</em> (pinakes), che significa "tavole" o "tavolette". Onora <strong>Callimaco di Cirene</strong> (305-240 a.C.) che intorno al 245 a.C. creò per la Biblioteca di Alessandria il primo catalogo bibliotecario sistematico della storia: i <em>Πίνακες τῶν ἐν πάσῃ παιδείᾳ διαλαμψάντων καὶ ὧν συνέγραψαν</em> ("Tavole di coloro che si sono distinti in ogni campo del sapere e delle loro opere").</p><p>Quest\'opera monumentale, composta da 120 rotoli, organizzava sistematicamente oltre 120.000 rotoli di papiro presenti nella biblioteca. Sebbene i <em>Pinakes</em> originali siano andati perduti, il loro metodo di catalogazione ha influenzato profondamente la biblioteconomia moderna.</p><p>Questo progetto prosegue quella tradizione millenaria di <strong>2.268 anni</strong> portando gli stessi principi di organizzazione e accessibilità del sapere nell\'era digitale.</p>', NULL, NULL, 1, 4, NOW(), NOW()),
('latest_books_title', 'Ultimi Arrivi', 'Scopri le ultime novità aggiunte al catalogo', NULL, NULL, NULL, 1, 5, NOW(), NOW()),
('genre_carousel', 'Esplora i generi principali', 'Scopri le nostre radici tematiche e lasciati ispirare dai titoli disponibili.', NULL, NULL, NULL, 1, 6, NOW(), NOW()),
('events', 'Eventi in Programma', 'Partecipa ai nostri prossimi incontri', NULL, NULL, NULL, 1, 7, NOW(), NOW()),
('cta', 'Pronto a iniziare?', 'Registrati ora e inizia a esplorare il nostro catalogo', NULL, 'Registrati Ora', '/register', 1, 8, NOW(), NOW());
SET FOREIGN_KEY_CHECKS=1;

-- Themes with Italian descriptions
INSERT INTO `themes` (`name`, `slug`, `version`, `author`, `description`, `active`, `settings`) VALUES
('Pinakes Classic', 'default', '1.0.0', 'Pinakes Team', 'Tema predefinito con colori magenta originali di Pinakes', 1, '{"colors": {"primary": "#d70161", "secondary": "#111827", "button": "#d70262", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Minimal', 'minimal-bw', '1.0.0', 'Pinakes Team', 'Design minimale con nero, grigio e bianco per un look pulito ed elegante', 0, '{"colors": {"primary": "#404040", "secondary": "#000000", "button": "#808080", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Ocean Blue', 'ocean-blue', '1.0.0', 'Pinakes Team', 'Tonalità blu oceano moderne e professionali per un\'interfaccia fresca', 0, '{"colors": {"primary": "#0284c7", "secondary": "#0c4a6e", "button": "#0ea5e9", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Forest Green', 'forest-green', '1.0.0', 'Pinakes Team', 'Verde smeraldo naturale che richiama la tranquillità della natura', 0, '{"colors": {"primary": "#059669", "secondary": "#064e3b", "button": "#10b981", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Sunset Orange', 'sunset-orange', '1.0.0', 'Pinakes Team', 'Arancione caldo e accogliente ispirato ai tramonti mediterranei', 0, '{"colors": {"primary": "#ea580c", "secondary": "#7c2d12", "button": "#f97316", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Burgundy', 'burgundy-red', '1.0.0', 'Pinakes Team', 'Rosso borgogna elegante e raffinato per un look sofisticato', 0, '{"colors": {"primary": "#be123c", "secondary": "#881337", "button": "#e11d48", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Teal Professional', 'teal-professional', '1.0.0', 'Pinakes Team', 'Verde acqua professionale perfetto per ambienti corporate', 0, '{"colors": {"primary": "#0d9488", "secondary": "#134e4a", "button": "#14b8a6", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Slate Gray', 'slate-gray', '1.0.0', 'Pinakes Team', 'Grigio ardesia moderno per un design neutro e contemporaneo', 0, '{"colors": {"primary": "#475569", "secondary": "#1e293b", "button": "#64748b", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Coral Warm', 'coral-warm', '1.0.0', 'Pinakes Team', 'Tonalità corallo calde e invitanti per un\'atmosfera accogliente', 0, '{"colors": {"primary": "#f43f5e", "secondary": "#9f1239", "button": "#fb7185", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Navy Classic', 'navy-classic', '1.0.0', 'Pinakes Team', 'Blu navy classico e intramontabile per un look istituzionale', 0, '{"colors": {"primary": "#1e40af", "secondary": "#1e3a8a", "button": "#3b82f6", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}');

-- CMS Pages - Italian only
INSERT INTO `cms_pages` VALUES (1,'about-us','it_IT','Chi Siamo','<h2>Benvenuto in Pinakes</h2>\n<p>Pinakes è un sistema di gestione bibliotecaria moderno, intuitivo e completamente gratuito. Costruito per semplificare la catalogazione dei libri, la gestione dei prestiti e l''amministrazione di biblioteche di ogni dimensione.</p>\n\n<h3>🎯 La Nostra Missione</h3>\n<p>Rendere la gestione bibliotecaria accessibile a tutti, senza costi di licenza e senza vincoli. Pinakes è 100% open source, libero e gratuito per tutti.</p>\n\n<h3>✨ Caratteristiche Principali</h3>\n<ul>\n    <li><strong>Catalogazione Intelligente:</strong> Importa automaticamente i dati da ISBN, organizza per categorie, autori e classificazioni personalizzate</li>\n    <li><strong>Gestione Prestiti:</strong> Sistema completo per gestire prestiti, scadenze, rinnovi e restituzioni</li>\n    <li><strong>Notifiche Automatiche:</strong> Promemoria via email per le scadenze dei prestiti e comunicazioni agli utenti</li>\n    <li><strong>Interfaccia Moderna:</strong> Design responsive ottimizzato per desktop, tablet e smartphone</li>\n    <li><strong>100% Open Source:</strong> Codice libero, personalizzabile e senza costi nascosti</li>\n</ul>\n\n<h3>🚀 Perché Scegliere Pinakes?</h3>\n<p>Pinakes nasce dall''esigenza di fornire uno strumento professionale, affidabile e gratuito per la gestione di biblioteche scolastiche, di associazioni e private. Non serve essere esperti informatici: l''interfaccia intuitiva permette a chiunque di iniziare subito.</p>\n\n<h3>📖 Inizia Oggi</h3>\n<p>Personalizza questa pagina con le informazioni sulla tua biblioteca, il tuo team e i tuoi servizi. Accedi al pannello admin (CMS &gt; Pagine) per modificare questo contenuto e renderlo unico.</p>\n\n<p><em>Questo è un contenuto di esempio. Personalizzalo per raccontare la storia della tua biblioteca!</em></p>',NULL,NULL,1,'2025-10-01 10:35:27','2025-10-01 10:35:27');
INSERT INTO `cms_pages` VALUES (2,'privacy-policy','it_IT','Informativa sulla Privacy','<h2>Informativa sulla Privacy</h2>\n<p>Questa è una pagina segnaposto per l''Informativa sulla Privacy. Personalizza questo contenuto in base alle normative applicabili (GDPR, Codice Privacy) e alle esigenze specifiche della tua biblioteca.</p>\n\n<h3>1. Titolare del Trattamento</h3>\n<p>[Inserisci qui i dati del titolare del trattamento: nome, indirizzo, email, telefono]</p>\n\n<h3>2. Dati Raccolti</h3>\n<p>I dati personali raccolti attraverso questo sistema includono:</p>\n<ul>\n    <li>Dati anagrafici (nome, cognome, data di nascita)</li>\n    <li>Dati di contatto (email, telefono, indirizzo)</li>\n    <li>Dati relativi ai prestiti effettuati</li>\n</ul>\n\n<h3>3. Finalità del Trattamento</h3>\n<p>I dati vengono trattati esclusivamente per:</p>\n<ul>\n    <li>Gestione anagrafica degli utenti</li>\n    <li>Gestione dei prestiti bibliotecari</li>\n    <li>Invio di comunicazioni relative ai prestiti (scadenze, rinnovi)</li>\n</ul>\n\n<h3>4. Diritti dell''Interessato</h3>\n<p>Gli utenti hanno diritto di accedere ai propri dati, richiederne la rettifica, la cancellazione o la limitazione del trattamento, come previsto dal Regolamento UE 2016/679 (GDPR).</p>\n\n<p><strong>IMPORTANTE:</strong> Questo è un modello di esempio. Consulta un professionista legale per redigere un''informativa privacy conforme alle normative vigenti.</p>\n\n<p><em>Accedi al pannello admin (CMS &gt; Pagine) per personalizzare questa pagina.</em></p>',NULL,NULL,1,'2025-10-01 10:35:27','2025-10-01 10:35:27');

-- Email Templates - Italian only
INSERT INTO `email_templates` VALUES (1,'admin_new_registration','it_IT','👤 Nuova richiesta di registrazione','\n            <h2>Nuova richiesta di registrazione</h2>\n            <p>Un nuovo utente ha richiesto l\'accesso a Pinakes:</p>\n            <p><strong>Dettagli utente:</strong></p>\n            <ul>\n                <li>Nome: {{nome}} {{cognome}}</li>\n                <li>Email: {{email}}</li>\n                <li>Codice tessera: {{codice_tessera}}</li>\n                <li>Data richiesta: {{data_registrazione}}</li>\n            </ul>\n            <p><a href=\"{{admin_users_url}}\" style=\"background-color: #3b82f6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;\">Gestisci Utenti</a></p>\n        ','Email inviata agli admin quando un nuovo utente si registra.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (2,'admin_new_review','it_IT','⭐ Nuova recensione da approvare','<h2>Nuova recensione da approvare</h2>\n<p>È stata ricevuta una nuova recensione per il libro:</p>\n<p><strong>Libro:</strong> {{libro_titolo}}</p>\n<div style=\"background-color: #fff7ed; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #f59e0b;\">\n    <p><strong>Valutazione:</strong> {{stelle}} stelle ⭐</p>\n    <p><strong>Utente:</strong> {{utente_nome}} ({{utente_email}})</p>\n    <p><strong>Data recensione:</strong> {{data_recensione}}</p>\n    <p><strong>Titolo:</strong> {{titolo_recensione}}</p>\n    <p><strong>Descrizione:</strong></p>\n    <p style=\"white-space: pre-line;\">{{descrizione_recensione}}</p>\n</div>\n<p style=\"text-align: center;\">\n    <a href=\"{{link_approvazione}}\" style=\"background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">Gestisci Recensione</a>\n</p>\n<p><em>Per approvare o rifiutare questa recensione, accedi al pannello admin.</em></p>','Inviata agli amministratori quando viene ricevuta una nuova recensione da approvare.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (3,'loan_approved','it_IT','✅ La tua richiesta di prestito è stata approvata!','<h2>La tua richiesta di prestito è stata approvata!</h2>\n<p>Ciao {{utente_nome}},</p>\n<p>Siamo lieti di informarti che la tua richiesta di prestito è stata <strong>approvata</strong>!</p>\n<p><strong>Dettagli del prestito:</strong></p>\n<ul>\n    <li>Libro: {{libro_titolo}}</li>\n    <li>Data inizio prestito: {{data_inizio}}</li>\n    <li>Data scadenza: {{data_fine}}</li>\n    <li>Durata: {{giorni_prestito}} giorni</li>\n</ul>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;\">\n    <p><strong>📦 Ritiro del libro</strong></p>\n    <p>{{pickup_instructions}}</p>\n</div>\n<p><strong>Importante:</strong> Ricorda di restituire il libro entro la data di scadenza. Riceverai un promemoria alcuni giorni prima della scadenza.</p>\n<p>Buona lettura!</p>','Inviata all\'utente quando un amministratore approva una richiesta di prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (4,'loan_rejected','it_IT','❌ La tua richiesta di prestito non è stata approvata','<h2>La tua richiesta di prestito non è stata approvata</h2>\n<p>Ciao {{utente_nome}},</p>\n<p>Ci dispiace informarti che la tua richiesta di prestito per il libro <strong>\"{{libro_titolo}}\"</strong> non è stata approvata.</p>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>Motivo:</strong></p>\n    <p>{{motivo_rifiuto}}</p>\n</div>\n<p>Se hai domande o desideri maggiori informazioni, non esitare a contattarci.</p>\n<p>Cordiali saluti,<br>Il team della biblioteca</p>','Inviata all\'utente quando un amministratore rifiuta una richiesta di prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (5,'loan_expiring_warning','it_IT','⚠️ Il tuo prestito sta per scadere','\n            <h2>Promemoria scadenza prestito</h2>\n            <p>Ciao {{utente_nome}},</p>\n            <p>Ti ricordiamo che il tuo prestito sta per scadere:</p>\n            <p><strong>Dettagli prestito:</strong></p>\n            <ul>\n                <li>Libro: {{libro_titolo}}</li>\n                <li>Data scadenza: {{data_scadenza}}</li>\n                <li>Giorni rimasti: {{giorni_rimasti}}</li>\n            </ul>\n            <div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n                <p><strong>⏰ Azione richiesta</strong></p>\n                <p>Per evitare penali, restituisci il libro entro la data di scadenza o contatta la biblioteca per un eventuale rinnovo.</p>\n            </div>\n            <p>Grazie per la collaborazione!</p>\n        ','Email inviata all\'utente 3 giorni prima della scadenza del prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (6,'loan_overdue_admin','it_IT','Prestito #{prestito_id} in ritardo','<h2>Prestito in ritardo</h2>\n<p>Il prestito <strong>#{{prestito_id}}</strong> è entrato nello stato <strong>in ritardo</strong>.</p>\n<ul>\n  <li><strong>Libro:</strong> {{libro_titolo}}</li>\n  <li><strong>Utente:</strong> {{utente_nome}} ({{utente_email}})</li>\n  <li><strong>Data prestito:</strong> {{data_prestito}}</li>\n  <li><strong>Data scadenza:</strong> {{data_scadenza}}</li>\n</ul>\n<p>Intervieni per contattare l\'utente e sollecitare la restituzione.</p>','Avvisa gli amministratori quando un prestito entra in ritardo.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (7,'loan_overdue_notification','it_IT','🚨 Prestito scaduto - Azione richiesta','\n            <h2>Prestito scaduto</h2>\n            <p>Ciao {{utente_nome}},</p>\n            <p>Il tuo prestito è scaduto e deve essere restituito immediatamente:</p>\n            <p><strong>Dettagli prestito:</strong></p>\n            <ul>\n                <li>Libro: {{libro_titolo}}</li>\n                <li>Data scadenza: {{data_scadenza}}</li>\n                <li>Giorni di ritardo: {{giorni_ritardo}}</li>\n            </ul>\n            <div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n                <p><strong>🚨 Azione urgente richiesta</strong></p>\n                <p>Il libro deve essere restituito immediatamente. Il ritardo nella restituzione può comportare sanzioni e la sospensione del servizio.</p>\n            </div>\n            <p>Contatta immediatamente la biblioteca per risolvere la situazione.</p>\n        ','Email inviata all\'utente quando il prestito è scaduto.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (8,'loan_request_notification','it_IT','📚 Nuova richiesta di prestito','\n            <h2>Nuova richiesta di prestito</h2>\n            <p>È stata ricevuta una nuova richiesta di prestito:</p>\n            <p><strong>Dettagli:</strong></p>\n            <ul>\n                <li>Libro: {{libro_titolo}}</li>\n                <li>Utente: {{utente_nome}} ({{utente_email}})</li>\n                <li>Data richiesta inizio: {{data_inizio}}</li>\n                <li>Data richiesta fine: {{data_fine}}</li>\n                <li>Data richiesta: {{data_richiesta}}</li>\n            </ul>\n            <p><a href=\"{{approve_url}}\" style=\"background-color: #10b981; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;\">Gestisci Richiesta</a></p>\n        ','Email inviata agli admin quando un utente richiede un prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (9,'user_account_approved','it_IT','Account approvato - Benvenuto in biblioteca!','\n            <h2>Il tuo account è stato approvato!</h2>\n            <p>Ciao {{nome}} {{cognome}},</p>\n            <p>Siamo lieti di informarti che il tuo account è stato approvato da un amministratore.</p>\n            <p>Ora puoi accedere al sistema e iniziare a prenotare libri!</p>\n            <p><strong>Dettagli del tuo account:</strong></p>\n            <ul>\n                <li>Email: {{email}}</li>\n                <li>Codice tessera: {{codice_tessera}}</li>\n            </ul>\n            <p><a href=\"{{login_url}}\" style=\"background-color: #3b82f6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;\">Accedi ora</a></p>\n            <p>Benvenuto nella nostra biblioteca digitale!</p>\n        ','Email inviata quando un admin approva direttamente l\'account senza richiedere verifica email.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (10,'user_activation_with_verification','it_IT','Attiva il tuo account - Verifica email','\n            <h2>Il tuo account è stato approvato!</h2>\n            <p>Ciao {{nome}} {{cognome}},</p>\n            <p>Siamo lieti di informarti che il tuo account è stato approvato da un amministratore.</p>\n            <p>📧 <strong>Verifica la tua email</strong></p>\n            <p>Per completare l\'attivazione, clicca sul pulsante qui sotto per verificare il tuo indirizzo email:</p>\n            <p style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"{{verification_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block;\">✅ Verifica Email</a>\n            </p>\n            <p><strong>Dettagli del tuo account:</strong></p>\n            <ul>\n                <li>Email: {{email}}</li>\n                <li>Codice tessera: {{codice_tessera}}</li>\n            </ul>\n            <div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n                <p><strong>⏰ Importante</strong></p>\n                <p>Il link di verifica è valido per 7 giorni. Dopo la verifica potrai accedere al sistema e prenotare libri.</p>\n            </div>\n            <p>Se non hai richiesto questa registrazione, puoi ignorare questa email.</p>\n        ','Email inviata quando un admin approva l\'account richiedendo la verifica email.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (11,'user_registration_pending','it_IT','Registrazione ricevuta - In attesa di approvazione','\n            <h2>Benvenuto {{nome}} {{cognome}}!</h2>\n            <p>La tua richiesta di registrazione è stata ricevuta con successo.</p>\n            <p><strong>Dettagli account:</strong></p>\n            <ul>\n                <li>Email: {{email}}</li>\n                <li>Codice tessera: {{codice_tessera}}</li>\n                <li>Data registrazione: {{data_registrazione}}</li>\n            </ul>\n            {{sezione_verifica}}\n            <div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n                <p><strong>⏳ Account in attesa di approvazione</strong></p>\n                <p>Il tuo account è in attesa di approvazione da parte di un amministratore.\n                Riceverai una email di conferma una volta che l\'account sarà stato attivato.</p>\n            </div>\n            <p>Grazie per aver scelto Pinakes!</p>\n        ','Email inviata all\'utente dopo la registrazione, quando l\'account è in attesa di approvazione.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (12,'wishlist_book_available','it_IT','📖 Libro della tua wishlist ora disponibile!','\n            <h2>Buone notizie!</h2>\n            <p>Ciao {{utente_nome}},</p>\n            <p>Il libro che hai aggiunto alla tua wishlist è ora disponibile per il prestito:</p>\n            <div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n                <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">{{libro_titolo}}</h3>\n                <p style=\"margin: 5px 0;\"><strong>Autore:</strong> {{libro_autore}}</p>\n                <p style=\"margin: 5px 0;\"><strong>ISBN:</strong> {{libro_isbn}}</p>\n                <p style=\"margin: 5px 0;\"><strong>Disponibile da:</strong> {{data_disponibilita}}</p>\n            </div>\n            <div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n                <p><strong>✨ Prenota subito!</strong></p>\n                <p>Il libro è ora disponibile per la prenotazione. Affrettati prima che qualcun altro lo prenoti!</p>\n            </div>\n            <p style=\"text-align: center;\">\n                <a href=\"{{book_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">📚 Prenota Ora</a>\n                <a href=\"{{wishlist_url}}\" style=\"background-color: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">❤️ Gestisci Wishlist</a>\n            </p>\n            <p><em>Questo libro è stato automaticamente rimosso dalla tua wishlist.</em></p>\n        ','Email inviata quando un libro della wishlist diventa disponibile.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (13,'reservation_book_available','it_IT','📚 Libro prenotato pronto per il ritiro!','<h2>Il tuo libro è pronto per il ritiro!</h2>\n<p>Ciao {{utente_nome}},</p>\n<p>Siamo lieti di informarti che il libro che avevi prenotato è ora disponibile e pronto per il ritiro:</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">{{libro_titolo}}</h3>\n    <p style=\"margin: 5px 0;\"><strong>Autore:</strong> {{libro_autore}}</p>\n    <p style=\"margin: 5px 0;\"><strong>ISBN:</strong> {{libro_isbn}}</p>\n    <p style=\"margin: 5px 0;\"><strong>Periodo prestito:</strong> {{data_inizio}} - {{data_fine}}</p>\n</div>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;\">\n    <p><strong>📦 Prossimi passi</strong></p>\n    <p>Recati in biblioteca per ritirare il libro. Porta con te un documento di identità.</p>\n</div>\n<p style=\"text-align: center;\">\n    <a href=\"{{book_url}}\" style=\"background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">📖 Vedi Libro</a>\n    <a href=\"{{profile_url}}\" style=\"background-color: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;\">👤 I miei Prestiti</a>\n</p>\n<p><em>La prenotazione è stata convertita in un prestito in attesa di conferma del ritiro.</em></p>','Email inviata quando un libro prenotato diventa disponibile e viene convertito in prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (14,'user_password_setup','it_IT','🔐 Imposta la tua password','<h2>Imposta la tua password</h2>\n<p>Ciao {{nome}} {{cognome}},</p>\n<p>Il tuo account su <strong>{{app_name}}</strong> è stato creato. Per iniziare ad utilizzare il sistema, devi impostare la tua password.</p>\n<div style=\"background-color: #f0f9ff; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #3b82f6;\">\n    <p><strong>🔑 Configura il tuo account</strong></p>\n    <p>Clicca sul pulsante qui sotto per impostare la tua password:</p>\n</div>\n<p style=\"text-align: center; margin: 30px 0;\">\n    <a href=\"{{reset_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block;\">🔐 Imposta Password</a>\n</p>\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏰ Importante</strong></p>\n    <p>Il link è valido per 24 ore. Se scade, contatta un amministratore per riceverne uno nuovo.</p>\n</div>\n<p>Se non hai richiesto questa email, puoi ignorarla.</p>','Email inviata ai nuovi utenti per impostare la password del loro account.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (15,'admin_invitation','it_IT','🎉 Invito come Amministratore','<h2>Benvenuto nel team!</h2>\n<p>Ciao {{nome}} {{cognome}},</p>\n<p>Sei stato invitato come amministratore su <strong>{{app_name}}</strong>.</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">Le tue credenziali</h3>\n    <p>Come amministratore, avrai accesso a:</p>\n    <ul>\n        <li>Gestione catalogo libri</li>\n        <li>Gestione utenti e prestiti</li>\n        <li>Impostazioni del sistema</li>\n        <li>Report e statistiche</li>\n    </ul>\n</div>\n<p><strong>Per iniziare:</strong></p>\n<ol>\n    <li>Imposta la tua password cliccando il pulsante qui sotto</li>\n    <li>Accedi al pannello di amministrazione</li>\n</ol>\n<p style=\"text-align: center; margin: 30px 0;\">\n    <a href=\"{{reset_url}}\" style=\"background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block; margin: 10px;\">🔐 Imposta Password</a>\n    <a href=\"{{dashboard_url}}\" style=\"background-color: #3b82f6; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block; margin: 10px;\">📊 Dashboard Admin</a>\n</p>\n<div style=\"background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n    <p><strong>⏰ Importante</strong></p>\n    <p>Il link per impostare la password è valido per 24 ore.</p>\n</div>\n<p>Benvenuto nel team!</p>','Email inviata quando un utente viene invitato come amministratore.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (16,'loan_pickup_ready','it_IT','📦 Libro pronto per il ritiro!','<h2>Libro pronto per il ritiro!</h2>\n<p>Ciao {{utente_nome}},</p>\n<p>Siamo lieti di informarti che il tuo libro è pronto per essere ritirato!</p>\n<div style=\"background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;\">\n    <h3 style=\"color: #1e40af; margin: 0 0 10px 0;\">{{libro_titolo}}</h3>\n    <p style=\"margin: 5px 0;\"><strong>Periodo prestito:</strong> {{data_inizio}} - {{data_fine}}</p>\n    <p style=\"margin: 5px 0;\"><strong>Scadenza ritiro:</strong> {{scadenza_ritiro}}</p>\n</div>\n<div style=\"background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;\">\n    <p><strong>📦 Come ritirare</strong></p>\n    <p>{{pickup_instructions}}</p>\n</div>\n<p>Buona lettura!</p>','Inviata quando un prestito è stato approvato e il libro è pronto per il ritiro.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (17,'loan_pickup_expired','it_IT','⏰ Tempo per il ritiro scaduto','<h2>Tempo per il ritiro scaduto</h2>\n<p>Ciao {{utente_nome}},</p>\n<p>Purtroppo non hai ritirato il libro entro il tempo previsto.</p>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>Libro:</strong> {{libro_titolo}}</p>\n    <p><strong>Scadenza ritiro:</strong> {{scadenza_ritiro}}</p>\n</div>\n<p>Il prestito è stato automaticamente annullato e il libro è stato reso disponibile per altri utenti.</p>\n<p>Se desideri ancora questo libro, ti invitiamo a effettuare una nuova richiesta di prestito.</p>\n<p>Cordiali saluti,<br>Il team della biblioteca</p>','Inviata quando il tempo per ritirare un libro è scaduto e il prestito è stato annullato.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (18,'loan_pickup_cancelled','it_IT','❌ Ritiro annullato','<h2>Ritiro annullato</h2>\n<p>Ciao {{utente_nome}},</p>\n<p>Ti informiamo che il ritiro del seguente libro è stato annullato:</p>\n<div style=\"background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;\">\n    <p><strong>Libro:</strong> {{libro_titolo}}</p>\n    <p><strong>Motivo:</strong> {{motivo}}</p>\n</div>\n<p>Il libro è stato reso disponibile per altri utenti. Se desideri ancora questo libro, ti invitiamo a effettuare una nuova richiesta di prestito.</p>\n<p>Cordiali saluti,<br>Il team della biblioteca</p>','Inviata quando un ritiro viene annullato dall''amministratore.',1,NULL,NULL);

-- ============================================================================
-- System Settings - Complete default configuration
-- These replace the old storage/settings.json file
-- ============================================================================

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`, `updated_at`) VALUES
-- App settings
('app', 'name', 'Pinakes', 'Application name', NOW()),
('app', 'logo_path', '', 'Path to application logo', NOW()),
('app', 'footer_description', 'Il tuo sistema Pinakes per catalogare, gestire e condividere la tua collezione libraria.', 'Footer description', NOW()),
('app', 'locale', 'it_IT', 'Default application locale', NOW()),
('app', 'social_facebook', '', 'Facebook profile URL', NOW()),
('app', 'social_twitter', '', 'Twitter profile URL', NOW()),
('app', 'social_instagram', '', 'Instagram profile URL', NOW()),
('app', 'social_linkedin', '', 'LinkedIn profile URL', NOW()),
('app', 'social_bluesky', '', 'Bluesky profile URL', NOW()),

-- Le impostazioni email sono configurate dall'utente nello step 6 dell'installer
-- Nessun valore predefinito qui per evitare di sovrascrivere le scelte dell'utente

-- Registration settings
('registration', 'require_admin_approval', '1', 'Require admin approval for new registrations', NOW()),

-- Contacts page settings
('contacts', 'page_title', 'Contattaci', 'Contacts page title', NOW()),
('contacts', 'page_content', '<p>Contattaci per qualsiasi informazione.</p>', 'Contacts page content', NOW()),
('contacts', 'contact_email', '', 'Contact email address', NOW()),
('contacts', 'contact_phone', '', 'Contact phone number', NOW()),
('contacts', 'google_maps_embed', '', 'Google Maps embed code', NOW()),
('contacts', 'privacy_text', 'I tuoi dati sono protetti secondo la nostra privacy policy.', 'Privacy disclaimer text', NOW()),
('contacts', 'recaptcha_site_key', '', 'reCAPTCHA site key', NOW()),
('contacts', 'recaptcha_secret_key', '', 'reCAPTCHA secret key', NOW()),
('contacts', 'notification_email', '', 'Email where contact form submissions are sent', NOW()),

-- Privacy page settings
('privacy', 'page_title', 'Privacy Policy', 'Privacy policy page title', NOW()),
('privacy', 'page_content', '<p>La tua privacy è importante per noi.</p>', 'Privacy policy content', NOW()),
('privacy', 'cookie_banner_enabled', '1', 'Enable cookie consent banner', NOW()),
('privacy', 'cookie_banner_language', 'it', 'Cookie banner language', NOW()),
('privacy', 'cookie_banner_country', 'it', 'Cookie banner country', NOW()),
('privacy', 'cookie_statement_link', '', 'Link to cookie statement', NOW()),
('privacy', 'cookie_technologies_link', '', 'Link to cookie technologies page', NOW()),
('privacy', 'cookie_policy_content', '', 'Cookie policy page content', NOW()),

-- Cookie banner settings
('cookie_banner', 'banner_description', '<p>Utilizziamo i cookie per migliorare la tua esperienza. Continuando a visitare questo sito, accetti il nostro uso dei cookie.</p>', 'Cookie banner description', NOW()),
('cookie_banner', 'accept_all_text', 'Accetta tutti', 'Accept all button text', NOW()),
('cookie_banner', 'reject_non_essential_text', 'Rifiuta non essenziali', 'Reject non-essential button text', NOW()),
('cookie_banner', 'preferences_button_text', 'Preferenze', 'Preferences button text', NOW()),
('cookie_banner', 'save_selected_text', 'Accetta selezionati', 'Save selected button text', NOW()),
('cookie_banner', 'preferences_title', 'Personalizza le tue preferenze sui cookie', 'Preferences modal title', NOW()),
('cookie_banner', 'preferences_description', '<p>Rispettiamo il tuo diritto alla privacy. Puoi scegliere di non consentire alcuni tipi di cookie. Le tue preferenze si applicheranno all\'intero sito web.</p>', 'Preferences modal description', NOW()),
('cookie_banner', 'cookie_essential_name', 'Cookie Essenziali', 'Essential cookies name', NOW()),
('cookie_banner', 'cookie_essential_description', 'Questi cookie sono necessari per il funzionamento del sito e non possono essere disabilitati.', 'Essential cookies description', NOW()),
('cookie_banner', 'show_analytics', '1', 'Show analytics cookies option', NOW()),
('cookie_banner', 'cookie_analytics_name', 'Cookie Analitici', 'Analytics cookies name', NOW()),
('cookie_banner', 'cookie_analytics_description', 'Questi cookie ci aiutano a capire come i visitatori interagiscono con il sito web.', 'Analytics cookies description', NOW()),
('cookie_banner', 'show_marketing', '1', 'Show marketing cookies option', NOW()),
('cookie_banner', 'cookie_marketing_name', 'Cookie di Marketing', 'Marketing cookies name', NOW()),
('cookie_banner', 'cookie_marketing_description', 'Questi cookie vengono utilizzati per fornire annunci personalizzati.', 'Marketing cookies description', NOW()),

-- Advanced settings
('advanced', 'custom_js_essential', '', 'Custom JavaScript for essential cookies', NOW()),
('advanced', 'custom_js_analytics', '', 'Custom JavaScript for analytics cookies', NOW()),
('advanced', 'custom_js_marketing', '', 'Custom JavaScript for marketing cookies', NOW()),
('advanced', 'custom_header_css', '', 'Custom CSS for header', NOW()),
('advanced', 'custom_header_js', '', 'Custom JavaScript for header', NOW()),
('advanced', 'days_before_expiry_warning', '3', 'Days before card expiry warning', NOW()),
('advanced', 'sitemap_last_generated_at', '', 'Last sitemap generation timestamp', NOW()),
('advanced', 'sitemap_last_generated_total', '0', 'Total URLs in last generated sitemap', NOW()),
('advanced', 'api_enabled', '0', 'Enable API access', NOW()),

-- Label printing settings
('label', 'width', '25', 'Label width in mm', NOW()),
('label', 'height', '38', 'Label height in mm', NOW()),
('label', 'format_name', '25x38mm (Standard)', 'Label format name', NOW()),

-- API settings
('api', 'enabled', '0', 'Enable API globally', NOW()),

-- Social sharing settings
('sharing', 'enabled_providers', 'facebook,x,whatsapp,email', 'Provider di condivisione social abilitati nella pagina dettaglio libro', NOW())
ON DUPLICATE KEY UPDATE
    setting_value = VALUES(setting_value),
    description = VALUES(description),
    updated_at = NOW();

-- Seed data for languages table
-- Issue #108: seed ALL shipped locales, not just the installer-chosen one,
-- so users whose `utenti.locale` differs from the install default
-- (e.g. a de_DE user on an it_IT install) can still have their locale
-- restored by RememberMeMiddleware → I18n::setLocale(), which gates on
-- `languages` table membership.
-- FIX F020: added ON DUPLICATE KEY UPDATE so re-running this seeder on an
-- existing DB (recovery / reinstall-test.sh path) doesn't fail with a
-- duplicate-key error on `languages.code`. Mirrors data_de_DE.sql:319.
-- FIX F023: total_keys/translated_keys/completion_percentage updated to real
-- JSON key counts (jq '[paths(scalars)] | length'): it_IT=493, en_US=4653,
-- de_DE=4653, fr_FR=4993. Previous values (2015/4009/4080) were stale and
-- inconsistent with migrate_0.7.5.sql (which used 4145). Fresh installs now
-- match the actual translation file contents.
INSERT INTO `languages` (`code`, `name`, `native_name`, `flag_emoji`, `is_default`, `is_active`, `translation_file`, `total_keys`, `translated_keys`, `completion_percentage`) VALUES
('it_IT', 'Italian', 'Italiano', '🇮🇹', 1, 1, NULL, 493, 493, 100.00),
('en_US', 'English', 'English', '🇬🇧', 0, 1, 'locale/en_US.json', 4653, 4653, 100.00),
('de_DE', 'German', 'Deutsch', '🇩🇪', 0, 1, 'locale/de_DE.json', 4653, 4653, 100.00),
('fr_FR', 'French', 'Français', '🇫🇷', 0, 1, 'locale/fr_FR.json', 4993, 4993, 100.00)
ON DUPLICATE KEY UPDATE name = VALUES(name), native_name = VALUES(native_name), flag_emoji = VALUES(flag_emoji), translation_file = VALUES(translation_file), total_keys = VALUES(total_keys), translated_keys = VALUES(translated_keys), completion_percentage = VALUES(completion_percentage), is_active = VALUES(is_active), is_default = VALUES(is_default);


SET FOREIGN_KEY_CHECKS=1;
